### ISSUE TITLE
Enhancement Request: Create GRPC Client from a GRPC Server instance in same process without Dialing

### ISSUE THREAD

**Issue by veqryn** [grpc/grpc-go#2271] opened 2018-08-21 07:54 UTC
I would like to be able to create a GRPC Client and have it talk to my existing GRPC Server within the same process, without sending network traffic through loopback/localhost.

I want to do this because I am hosting a GRPC Server and a GRPC Gateway in the same process (https://github.com/grpc-ecosystem/grpc-gateway).
The gateway requires a GRPC Client, which means that the GRPC Gateway uses the GRPC Client to send traffic on localhost loopback to the GRPC Server.

For example, I would like something roughly like this:
```go
// GRPC Server
grpcServer := grpc.NewServer()
pb.RegisterPixelServer(grpcServer, myService)
// Serve and listen in a goroutine...

// GRPC Gateway
mux := runtime.NewServeMux()
grpcClient := pb.NewClientAdaptor(grpcServer, myService)
err := gw.RegisterPixelHandlerClient(ctx, mux, grpcClient)
// Serve up the gateway mux in a goroutine...
```

I realize that it is possible to manually make `myService` satisfy both `MyServiceServer` and `MyServiceClient` interfaces on a generated golang proto file.
However doing so would mean that grpc.CallOption's would get ignored, and I would also lose out on grpc's interceptors and stats handling, and other things that the grpc client and server are doing that would be bypassed by handling it directly.

### What version of gRPC are you using?
1.14.0

### What version of Go are you using (`go version`)?
1.10

### What operating system (Linux, Windows, …) and version?
Windows 10

**Comment by menghanl** [comment] 2018-08-21 16:47
This looks like a duplicate of #906.

We are working on a transport redesign to enable custom transports, including in-process transport. Please see more detailed updates in the issue.

Closing this now. Please reply if you have other concerns.

**Closed by menghanl** 2018-08-21 16:47 UTC
