### ISSUE TITLE
Possible goroutine/connection leak

### ISSUE THREAD

**Issue by ewang** [grpc/grpc-go#1341] opened 2017-06-29 03:05 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
server: grpc-go 1.4.0, client: Python grpcio 1.4.0

### What version of Go are you using (`go version`)?
go1.8.3

### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04

### What did you do?
Prior to grpc-go 1.3, I'd see connection leakage (they seem to be closed by the client w/o the server knowing about it), and goroutines would start leaking. Post 1.3, the keepalive functionality helped close those "abandoned" connections.

I've currently set the keepalive parameters to: MaxConnectionIdle: 1 hr, Time: 1 hr.

Oddly the rate of leakage happens faster when RPC transaction counts are low. Not sure if this is something w/ grpc on the Python side.

<img width="1036" alt="screen shot 2017-06-28 at 10 20 06 am" src="https://user-images.githubusercontent.com/124396/27669678-ef37954e-5c3c-11e7-9bfc-c0adf9ec76da.png">
<img width="353" alt="screen shot 2017-06-28 at 10 20 37 am" src="https://user-images.githubusercontent.com/124396/27669680-ef3f1bf2-5c3c-11e7-92a1-bb91ae809e65.png">

### What did you expect to see?
Fairly steady connection/goroutine count.

### What did you see instead?
Goroutine count seems to go up as RPC transactions per minute goes down.

**Comment by MakMukhi** [comment] 2017-07-01 00:07
Hey,
Thanks for the detailed representation of the problem. However, the data seems very hard to believe. The number of go routines seems to be decreasing proportionally to the increase in number of RPCs. This can't be the case. Would you mind vetting the graphs further? 
Also, it'd really helpful if you can provide a reproduction of this issue.

**Comment by ewang** [comment] 2017-07-01 00:16
@MakMukhi It's odd to me as well. My only guess so far is that the Python/C-core is cycling channel connections frequently when activity is low, causing more broken connections which only gets cleaned up by the keepalive on server side after an hour.

**Comment by MakMukhi** [comment] 2017-07-12 23:36
That doesn't answer why would the goroutines increase during inactivity? Broken connections don't spawn new goroutines on Go server.

**Comment by MakMukhi** [comment] 2017-07-21 21:06
Since it's really hard to pursue this without a reliable reproduction and the fact that we haven't noticed anything similar. I'm going to go ahead and close this issue. Feel free to get back to us if you find something more or perhaps a reproduction. Thanks for your time and effort.

**Closed by MakMukhi** 2017-07-21 21:06 UTC
