### ISSUE TITLE
[Feature request] Add wasm support

### ISSUE THREAD

**Issue by MOZGIII** [grpc/grpc-go#2294] opened 2018-09-06 03:05 UTC
Hey guys!

Since Go has now wasm support as a target, have you considered implementing a version of grpc-go that would be usable from within the browser or nodejs (or any wasm runtime)?

Thanks is advance.

**Comment by mastersingh24** [comment] 2018-09-06 11:33
@MOZGIII  - For the browser, you may want to check out [gRPC Web](https://github.com/grpc/grpc-web).

**Comment by nicolasnoble** [comment] 2018-09-06 12:39
Wasm, by design, doesn't have low level networking support, so this request is inherently impossible.

**Comment by MOZGIII** [comment] 2018-09-06 13:30
@nicolasnoble understandable. On the other hand, wasm on it's own does not have any networking support, but we can declare an API that nodejs can fulfill. Browsers are not a major concern for this, but the browser may be able to fulfill that API is at some point in the future too.
In fact, maybe it should be not in Go, but C.
@mastersingh24 thanks. I'm actually using gRPC-Web already, along with node-grpc.

**Comment by dfawley** [comment] 2018-09-06 16:04
/cc @johanbrandhorst 

@MOZGIII - See #2174.  It was not merged because we don't want so much special casing going on inside our transport (which is already in need of some cleanup).  Instead we'll be adding support for pluggable transports, and then a separate transport can be implemented for wasm.

**Comment by johanbrandhorst** [comment] 2018-09-06 16:17
I do plan on submitting a PR adding transparent WASM client support to this library when the transport interface is available. It'll either be merged and activated under the WASM build tag or I'll publish and maintain it on my public github. Watch this space :).

**Comment by johanbrandhorst** [comment] 2018-09-06 16:19
If you want to see #2174 in action, check out the demo on my talk about WASM: https://youtu.be/iTrx0BbUXI4?t=847.

**Comment by hsaliak** [comment] 2018-09-06 18:15
@MOZGIII -- trying to understand this request better, and I have some questions: What is the motivation for wanting something like this? Is this something that would be 'cool to have' or will it enable something critical for you?

**Comment by MOZGIII** [comment] 2018-09-06 18:58
@hsaliak tl;dr: it's purely a "cool to have" at this point.

The original idea for this PR was to use Go instead of `node-grpc` in a nodejs-based API gateway. I was elaborating on options to better integrate generated code with with TypeScript - which I resolved even before creating this issue (it doesn't seem to reduce the effort much) - so don't mind that, just mentioning it as a context.

After some time I though a bit and created this issue. It's not on our critical path, and is more like a nice to have. The benefits of it on it's own (without TypeScript definitions to allow type-checked code) would be to share interceptors and metadata handling procedures with the the Go code bases. Potentially sharing load balancing / discovery logic too - but we're more likely to solve it by introducing service mesh (i.e. istio or sth). And even interceptors/metadata stuff is solved differently.

We're already using gRPC-Web in browser, but I mainly envisioned using wasm grpc-go at the server-side in a nodejs server. That means, Go-via-C or other kind of nodejs binding would work too.

Also, I was just curious if somebody is working on this - cause it's cool :)

Now if I think about it, I'd rather have #906 done so that wasm support can be added by users on a need basis, rather than explicitly supporting it. However, it's a good idea to test the baseline - whether the code builds under wasm or not (with some dummy transport) - and keep that part working.

**Comment by MOZGIII** [comment] 2018-09-06 19:01
Transport support for wasm would be effectively solved by #906, but ensuring that the code build with dummy transport should be address explicitly. Is that sense, I'd keep this issue blocked #906 is finished, implemented tests to make sure wasm works (with dummy transport), and only then close this one.

**Comment by dalu** [comment] 2019-05-27 11:02
This issue is the top result when googling for "golang wasm grpc" or "golang webassemble grpc".
I'm trying to write a simple "waiting game", aka press button and wait, prototype.
And I was wondering if I should pick js and websockets which has its own set of issues esp on unstable connections, eventsource or make something proper with grpc.
Seems like I won't be using grpc. grpc-web isn't really there yet and requires too much effort on the server side, e.g. custom module for nginx.

**Comment by johanbrandhorst** [comment] 2019-05-27 12:33
@dalu gRPC-Web is production ready. See https://grpc.io/blog/state-of-grpc-web/ for more information. Go WASM is not production ready, however.

**Comment by dalu** [comment] 2019-05-27 13:07
In reality it is not. It has issues with Angular and Typescript. It needs a custom nginx module.
In reality it's not production ready.

**Comment by johanbrandhorst** [comment] 2019-05-27 13:26
This isn't really the place for this discussion, but many companies are already using it in production, and it does not require a custom nginx module anymore. I'd be happy to discuss any questions you might have about it (I am the author of the blog post on the official gRPC blog), if you want to learn more. You can find me under `@jbrandhorst` on Gophers slack or on twitter.

**Comment by dalu** [comment] 2019-05-27 16:27
I don't use Slack or Twitter and those are not appropriate platforms either.
Supporting Clojurescript only isn't enough.
Typescript support is still experimental and NOT production ready.

And yes you do require a custom nginx module, using envoy is not an option. You call it extension. This module is not part of the official nginx release.

> It originally shipped with a proxy implemented as an NGINX extension16, but has since doubled down on an Envoy proxy HTTP filter17, which is available in all versions since v1.4.0.

Having to compile some extra module is too much. Because one also needs to keep it updated.
So no it's not production ready without jumping through too many hoops.

It's not there yet.

I have wasted time on it before and I'm not going to do so again. Calling something takes a bit more than just giving it a v1.0 tag.
grpc-web is not an option for me or any single developer using typescript or angular and nginx on the front.
Maybe in some hipster yuppy companies who can afford to waste resources.

**Comment by tarndt** [comment] 2019-12-20 23:38
I ran into this problem and created a [solution](https://github.com/tarndt/wasmws)! Hopefully this is useful to you guys too. Its pretty young so PRs/testing is very welcome. :smile_cat:

**Comment by johanbrandhorst** [comment] 2019-12-21 08:06
This is a really cool use of the Go grpc interfaces, but I feel obliged to point out that Denys Smirnov did it first: https://github.com/dennwc/dom/tree/master/examples/grpc-over-ws. Well done regardless!

**Comment by tarndt** [comment] 2019-12-21 15:18
Thanks @johanbrandhorst  I didn't realize that existed.

>but I feel obliged to point out that Denys Smirnov did it first

Now I feel silly, I'll have to read his implementation and compare them. Nothing like feeling like you did something useful and then realizing you wasted your time :crying_cat_face: .

**Comment by johanbrandhorst** [comment] 2019-12-22 08:01
> Now I feel silly, I'll have to read his implementation and compare them. Nothing like feeling like you did something useful and then realizing you wasted your time 😿 .

Don't be discouraged! It is a really clever use of interfaces, it wasn't my intention to put you down. I'm sure you learned a lot while playing around with it, and time learning is never wasted 😄.

**Comment by tarndt** [comment] 2019-12-23 15:15
> time learning is never wasted

True true. And a lesson to do a better job Googling before getting started lol.

Looking closer at the implementations are they are quite different under the hood. I need to run some proper benchmarks but at a glance I would assume:

- Code that depends on deadlines will not work with Mr. Smirnov's implementation (deadlines are TODO).
- Mr. Smirnov's implementation will perform slightly better in general cases, less work per read.
- Mr. Smirnov's implementation will consume significantly more memory in situations when large messages have been received (as used buffer is never released).

Talking a closer look, I think that I will update mine implementation be a hybrid using his strategy for common cases (better performance) and retaining mine for edge cases (better worst case handling). This will make things more complex, but software engineering... always about the tradeoffs... :smile_cat:

**Comment by logicethos** [comment] 2020-08-12 00:48
Just want to add, this is a sorely missing feature in Q3 2020.  I wrote my Go WASM app expecting grpc to just work.  I wish I had checked first.

**Comment by armin-th** [comment] 2020-08-31 03:23
> This is a really cool use of the Go grpc interfaces, but I feel obliged to point out that Denys Smirnov did it first: https://github.com/dennwc/dom/tree/master/examples/grpc-over-ws. Well done regardless!

Question for the issue moderators, Is this not the correct way about it or are you keeping this issue open because the quoted example has limitations I'm not aware of?

**Comment by johanbrandhorst** [comment] 2020-08-31 06:41
Using websockets as a net.Conn introduces a lot of overhead, and a proper solution would require a pluggable transport interface that would allow the design of a transport that takes advantage web-specific technologies, for example, the grpcweb protocol. This would also allow go Wasm frontends to be compatible with any grpcweb backend.

**Comment by menghanl** [comment] 2021-05-03 23:56
Closing this issue. Custom transport support is tracked in #906

**Closed by menghanl** 2021-05-03 23:56 UTC
Labels: P3, Status: Blocked, Type: Feature
