### ISSUE TITLE
option.WithGRPCConnectionPool fails randomly

### ISSUE THREAD

**Issue by pongad** [grpc/grpc-go#1432] opened 2017-08-09 03:57 UTC
Please answer these questions before submitting your issue.

issue originally posted at https://github.com/GoogleCloudPlatform/google-cloud-go/issues/713

### What version of gRPC are you using?
1.6.0-dev.
Commit 73041be9060cc8b77986cfb0343d9e690f312049

### What version of Go are you using (`go version`)?
go version go1.9rc2 linux/amd64

### What operating system (Linux, Windows, …) and version?
Ubuntu Trusty

### What did you do?
Consider program below
```go
package main

import (
	"log"

	"golang.org/x/net/context"
	"google.golang.org/api/option"
	"google.golang.org/api/transport"
	pb "google.golang.org/genproto/googleapis/iam/v1"
)

func main() {
	ctx := context.Background()
	conn, err := transport.DialGRPC(ctx, option.WithEndpoint("pubsub.googleapis.com:443"), option.WithGRPCConnectionPool(2))
	if err != nil {
		log.Fatal("can't dial", err)
	}
	c := pb.NewIAMPolicyClient(conn)
	perms, err := c.TestIamPermissions(ctx, &pb.TestIamPermissionsRequest{
		Resource: "foo",
		Permissions: []string{
			"pubsub.topics.publish",
			"pubsub.topics.update",
		},
	})
	if err != nil {
		log.Fatal("can't test", err)
	}
	log.Println(perms)
}
```
### What did you see instead?
If I delete the `option.WithGRPCConnectionPool`, everything works fine.
With the connection pool option, the program
1. sometimes succeeds
2. sometimes fails with `rpc error: code = Unavailable desc = grpc: the connection is closing` from [here](https://github.com/grpc/grpc-go/blob/4e56696c6c5a8cd7b711a1eb8936463559361da5/clientconn.go#L834)
3. sometimes fails with `rpc error: code = Unavailable desc = there is no address available` from [here](https://github.com/grpc/grpc-go/blob/4e56696c6c5a8cd7b711a1eb8936463559361da5/balancer.go#L313)

I don't know the code base well enough to tell what's causing (2).

I think (3) is caused by the following:
- `roundRobin.Start` [spins up](https://github.com/grpc/grpc-go/blob/4e56696c6c5a8cd7b711a1eb8936463559361da5/balancer.go#L231) a goroutine to run `watchAddrUpdates`, which populates `rr.addrs`.
- `roundRobin.Get` uses `rr.addrs`.

However, there is no synchronization to make sure `watchAddrUpdates` is called before `Get`, so `Get` could observe that there is no connection before `watchAddrUpdates` could do anything. Would it make sense to call `watchAddrUpdates` once before `Start` returns?

**Comment by menghanl** [comment] 2017-08-09 19:31
The root cause of this issue is that, the `ClientConn` returned by a non-blocking dial is not immediately ready to use (connections are not established for example).

Our exiting handling of `FailFast` is flawed, so if you make an RPC on a non-ready `ClientConn`, the RPC may fail as you saw.

A quick fix for this is to do a blocking dial using [`WithBlock`](https://godoc.org/google.golang.org/grpc#WithBlock), so that in the returned `ClientConn`, there's at least one ready connection to use, then FailFast RPCs will still succeed on this connection.
Or you can make the RPC non-failfast using [`FailFast`](https://godoc.org/google.golang.org/grpc#FailFast), this should also fix the issue you saw.
I tried both, and the failure seems to be gone with these.

We are working on a fix for the FailFast issue, as part of the new Resolver and Balancer implementation (#1388).
In the new implementation, we can better handle FailFast RPCs on a connecting `ClientConn`, issues like this will not happen.

**Comment by pongad** [comment] 2017-08-11 03:33
@menghanl noted. I don't see another issue for Balancer and Resolver failing specifically so I'll leave it up to you if you want to close this as duplicate.

**Comment by dfawley** [comment] 2017-08-24 22:49
Let's track the wait for ready bug via #1463.

**Closed by dfawley** 2017-08-24 22:49 UTC
