### ISSUE TITLE
failed to receive the preface from client -- triggered by tcp health check

### ISSUE THREAD

**Issue by imoverclocked** [grpc/grpc-go#875] opened 2016-09-02 18:00 UTC
I'm running a gRPC server in an environment that checks health via tcp open or tcp half-open. This triggers:

```
2016/09/02 17:58:25 transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 1.1.1.1:31703->2.2.2.2:54388: read: connection reset by peer
```

which fills up logs over time. Any chance of squelching the message, even with an option?

https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L231

Cheers.

**Comment by iamqizhao** [comment] 2016-09-02 18:08
we are working on improving grpc logging (this should only appear in debugging mode).

**Comment by enm10k** [comment] 2017-01-17 17:15
I had the same issue.
And I want this to be fixed for our production use.

> we are working on improving grpc logging (this should only appear in debugging mode).

Is there any work-in-progress branch as public?
If no one is working on this now, I'll do.

**Comment by MakMukhi** [comment] 2017-01-17 19:11
Hey,

We are working on this; There's a PR out. However, the engineer working on
it is ooo and we'll be able to give a status once he's back.

Best,
Mak

**Comment by enm10k** [comment] 2017-01-18 10:24
Thanks.
I'm waiting for he's back.

**Comment by hsaliak** [comment] 2017-05-17 21:54
@MakMukhi @menghanl can you reference the PR here and close the issue if it's already resolved?

**Comment by CocoaWang** [comment] 2017-06-01 08:17
hi , do you have any solutions for this problem ? for i have met the same error.

**Comment by menghanl** [comment] 2017-06-01 18:14
Log spamming will be alleviated with grpclog changes.

We have https://github.com/grpc/grpc-go/pull/922 for the API change.
I also have the change to use different log levels in gRPC ready, will send that out when the API change is merged.

**Comment by CocoaWang** [comment] 2017-06-02 06:18
@menghanl  i have resolved my problem . The reason is that i set the wrong server-hostname when running tls

**Closed** 2017-10-12 20:27 UTC

**Comment by xusss** [comment] 2017-10-30 08:08
@imoverclocked 
This error is still existing for me with version [v1.7.0](https://github.com/grpc/grpc-go/blob/v1.7.0/transport/http2_server.go#L362)
Do you have any solutions for this problem?

**Comment by MakMukhi** [comment] 2017-10-30 17:21
@xuss Can you throw some more light on what exactly are you seeing?

1. Is your log spammed by errors originating in transport? Perhaps, consider setting your log verbosity level  to 1. [grpclog](https://godoc.org/google.golang.org/grpc/grpclog)

2. Are you unable to connect because of a specific transport error? Please share more information, possible a reproduction.
