### ISSUE TITLE
Suppress unnecesssary internal info logs from clientconn.go

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc-go#3918] opened 2020-10-01 18:23 UTC
### What did you do?
Run gRPC codelab.

### What did you expect to see?
Clean log.

### What did you see instead?
Unnecessary logs were dumped by default.
```
clientconn.go:162] [core]Channel Created
clientconn.go:249] [core]parsed scheme: ""
clientconn.go:255] [core]scheme "" not registered, fallback to default scheme
...
clientconn.go:681] [core]ClientConn switching balancer to "pick_first"
clientconn.go:696] [core]Channel switches to new LB policy "pick_first"
clientconn.go:737] [core]Subchannel Created
clientconn.go:737] [core]Subchannel(id:2) created
clientconn.go:1073] [core]Subchannel Connectivity change to CONNECTING
clientconn.go:1210] [core]Subchannel picks a new address "127.0.0.1:10000" to connect
clientconn.go:428] [core]Channel Connectivity change to CONNECTING
clientconn.go:1073] [core]Subchannel Connectivity change to READY
clientconn.go:428] [core]Channel Connectivity change to READY
...
clientconn.go:1437] [core]Subchannel Deleted
clientconn.go:1437] [core]Subchanel(id:2) deleted
clientconn.go:1029] [core]Channel Deleted
...
```

Note those logs weren't there by default before the import on 02/19.
Do we want to support verbosity level for internal logs or provide an easy way to disable those info logs?

**Comment by dfawley** [comment] 2020-10-01 20:43
These messages seem to meet the published standards for INFO log-level messages here: 

https://github.com/grpc/grpc-go/blob/master/Documentation/log_levels.md#info

Perhaps you want to disable grpc info logs instead?

**Comment by ZhouyihaiDing** [comment] 2020-10-07 20:34
There is no easy way to disable "info" logs for gRPC. The user needs to [create a custom logger](https://godoc.corp.google.com/pkg/google3/third_party/golang/grpc/grpclog/grpclog#SetLoggerV2) to discard those newly appeared logs. It would also be nice if we can provide an easy way to do so.

**Comment by dfawley** [comment] 2020-10-07 20:59
If you have an existing logger:

```go
type MyInfoSinkLogger struct {
	grpclog.LoggerV2  // Embed the primary logger
}

func (MyInfoSinkLogger) Info(...) { }    // Override Info funcs
func (MyInfoSinkLogger) Infoln(...) { }  // to nops, so Info logs
func (MyInfoSinkLogger) Infof(...) { }   // are ignored.
```

If not, you can use https://godoc.org/google.golang.org/grpc/grpclog#NewLoggerV2:

```go
	grpclog.SetLoggerV2(grpclog.NewLoggerV2(ioutil.Discard, <warning writer>, <error writer>)
```

**Comment by dfawley** [comment] 2020-10-07 21:02
> The user needs to create a custom logger

I forgot to mention: info logs are off by default for the default logger, and are only enabled by setting the environment variable `GRPC_GO_LOG_SEVERITY_LEVEL=info`.

**Comment by ZhouyihaiDing** [comment] 2020-10-07 21:43
Currently these logs are enabled by default in [glogger](https://github.com/grpc/grpc-go/blob/master/grpclog/glogger/glogger.go) which doesn't check `GRPC_GO_LOG_SEVERITY_LEVEL`.
The user needs to replace the log by `grpclog.SetLoggerV2` to disable these logs.
It's nice to have a similar switch like `GRPC_GO_LOG_SEVERITY_LEVEL` for glogger.

**Comment by dfawley** [comment] 2020-10-07 22:22
As part of the component logging #3617, we wanted to make this configurable per-module in addition to globally.  This feature still needs to be designed, but we should do that instead of adding knobs to the glogger (which isn't really recommended for most users since it parses command-line flags).

**Comment by dfawley** [comment] 2020-10-07 22:24
Let's call this a dupe of the new issue I made to track the above, #3937.

**Closed by dfawley** 2020-10-07 22:24 UTC
Labels: Status: Duplicate, Type: Feature
