### ISSUE TITLE
KeepAlive: Go bidi stream server sending GOAWAY, ENHANCE_YOUR_CALM to C++ client that has KeepAlive enabled

### ISSUE THREAD

**Issue by RahulMitra** [grpc/grpc-go#2202] opened 2018-07-04 00:24 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
```
C++: v1.10.0
Go: v1.12.0
```
### What version of Go are you using (`go version`)?
```
go version: 
go1.9.4 linux/amd64
```
### What operating system (Linux, Windows, …) and version?
```
uname -a:
Linux 10-144-27-126 4.4.0-111-generic #134~14.04.1-Ubuntu SMP Mon Jan 15 15:39:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### What did you do?

Golang server side:
```
grpcServer := grpc.NewServer(
    grpc.KeepaliveParams(
        keepalive.ServerParameters{
            Time:    (time.Duration(20) * time.Second),
            Timeout: (time.Duration(10) * time.Second),
        },
    ),
)
net.listen followed by grpcServer.Serve
```

C++ client:
```
int SECONDS = 1000;
grpc::ChannelArguments ch_args;    
ch_args.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, 20 * SECONDS);
ch_args.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 10 * SECONDS);
ch_args.SetInt(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 1);
ch_args.SetInt(GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS, 10 * SECONDS);
ch_args.SetInt(GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS, 20 * SECONDS);
ch_args.SetInt(GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA, 0);

auto grpc_channel_ = grpc::CreateCustomChannel(target, grpc::InsecureChannelCredentials(), ch_args);

ClientContext context;
std::unique_ptr<MyService::Stub> service_stub = MyService::NewStub(grpc_channel_);
std::shared_ptr<ClientReaderWriter<MyMessage, MyMessage> > stream(service_stub->Connect(&context));
```

### What did you expect to see?
Stream stays connected, with keepalive enabled.

### What did you see instead?
The go server side is closing the stream with GOAWAY error code.

On the C++ client side, I am receiving the following:
```
E0703 19:15:37.239106529   19810 chttp2_transport.cc:1097]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
```
this disconnects the stream, and when the client re-connects, it happens again.

I've also tried putting a KeepaliveEnforcementPolicy on the go server, so that it knows to expect pings, and I matched the parameters with the C++ client side. But still seeing the GOAWAY and error codes.
```
grpcServer := grpc.NewServer(
    grpc.KeepaliveParams(
        keepalive.ServerParameters{
            Time:    (time.Duration(20) * time.Second),
            Timeout: (time.Duration(10) * time.Second),
        },
    ),
    grpc.KeepaliveEnforcementPolicy(
        EnforcementPolicy{
            MinTime:             (time.Duration(20) * time.Second),
            PermitWithoutStream: true,
        },
    ),
)
```
I am aware that there's a version mis-match between C++ GRPC and go GRPC, but figured that this shouldn't be the issue?

**Comment by dfawley** [comment] 2018-07-06 18:35
> this disconnects the stream, and when the client re-connects, it happens again.

This is unexpected..  It's very possible that, with 20s set on the client and 20s set on the server, a small amount of network jitter will cause an error to happen once.  However, the C client should be slowing its rate down when it sees `ENHANCE_YOUR_CALM`.  We do this in Go here:

https://github.com/grpc/grpc-go/blob/f3361fda2fe0734510c562684480f18ebb63ac33/clientconn.go#L1196-L1202

Can you try setting a 10 second `MinTime` on the Go server and see if the `GOAWAY`s still happen?

**Comment by RahulMitra** [comment] 2018-07-07 10:13
Thanks, that seems to have fixed it. After setting the `MinTime` to 10 seconds, I no longer see the `GOAWAY`s.

Just for my understanding, do you mind explaining why the issue was fixed by setting the server's `KeepaliveEnforcementPolicy.MinTime` to a value smaller than the keepalive time on the client?

According to the documentation for `KeepaliveEnforcementPolicy`:
```
MinTime is the minimum amount of time a client should wait before sending a keepalive ping.
```
And according to the documentation for `GRPC_ARG_KEEPALIVE_TIME_MS`:
```
After a duration of this time the client/server pings its peer to see if the transport is still alive.
```

From reading this, I had understood it to mean that if I set the client keepalive to 20 seconds, then the server enforcement policy should have the same value.

**Comment by dfawley** [comment] 2018-07-09 21:17
> Just for my understanding, do you mind explaining why the issue was fixed by setting the server's KeepaliveEnforcementPolicy.MinTime to a value smaller than the keepalive time on the client?

If both are exactly the same, then a little network jitter will mean that the server believes the client is being abusive.  Example:

Client and server configured for 20s ping/enforcement time
- T=0s: client sends ping
- T=0.5s: server receives ping
- T=20s: client sends ping
- T=20.4s: server receives ping

Because the server received the second ping 19.9s after the first ping, it will treat it as abusive and tell the client to enhance its calm.  If the server's enforcement time was 10s, then 19.9s is well over that amount and everything is fine.

The client is *supposed* to reduce its ping frequency when this happens.  If that is working correctly, the errors should stop.  If you are seeing C clients *continually* getting these errors, we can file a bug against the C repo, as it's likely the problem lies there.

**Comment by dfawley** [comment] 2018-07-12 20:18
@yashykt could you look into this from the C-client-side, please? It seems the client isn't scaling its ping timing when it gets pushback from the server.

**Comment by yashykt** [comment] 2018-07-12 21:23
The C++ client also has the same scaling mechanism. Without extensive logs I won't be able to tell for sure, but possibly, this is being caused by GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA being set to 0 which means that the client will continue sending pings even if it does not have data to send. Please set it to 1/2 instead.

**Comment by dfawley** [comment] 2018-07-13 20:40
@yashykt is that by design?  It seems like the scaling should be honored regardless of the pings-per-data-frame setting.

**Comment by yashykt** [comment] 2018-07-14 01:11
Just for context - this is where C++ scales the keepalive time

https://github.com/grpc/grpc/blob/f9f5c67aff91e4ad26371b0a2482a5011ab45226/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L1098

**Comment by dfawley** [comment] 2018-07-16 16:41
> I am guessing that scaling is being honored. It's just that even after scaling, we are sending pings without data even though are spaced out. The server is probably not expecting that.

This doesn't sound right, because our server doesn't check for data frames in its enforcement.  Also, `PermitWithoutStream` is set, meaning pings even while idle is OK.

@RahulMitra, can you try this out, please?  Set GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA to 1 and have client and server both set to 20s ping time/enforcement as in the initial report.

**Comment by yashykt** [comment] 2018-07-16 18:21
@RahulMitra One more thing to verify - Please try using the latest version instead. 
If the error persists after these experiments, I would like to have a look at the logs too with env var GRPC_TRACE set to 'http' and GRPC_VERBOSITY set to DEBUG
It'll also be useful to get a gist of your trial code, so we can reproduce it easily.

**Comment by RahulMitra** [comment] 2018-07-16 18:54
Apologies for the late response - was traveling last week. 

Thanks for the help with this. Will run these tests today and get back to you, and will also provide you a full gist of the trial code (allows for easy parameterizing of these various channel args) so you can further test.

**Comment by dfawley** [comment] 2018-07-26 20:16
@RahulMitra any updates on your testing?

**Comment by RahulMitra** [comment] 2018-07-30 20:37
@dfawley 

When following your suggestion to set GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA to 1 and have client and server both set to 20s ping time/enforcement as initially reported, I no longer see any GOAWAYS. However, if I set GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA to 0, the GOAWAYs do return as initially reported.

Just for clarity, here are the parameters again:

**Golang server:**
```
keepalive.ServerParameters Time: 20 Seconds
keepalive.ServerParameters Timeout: 10 Seconds
keepalive.EnforcementPolicy MinTime: 20 Seconds
keepalive.EnforcementPolicy PermitWithoutStream: True
```

**C++ client:**
```
GRPC_ARG_KEEPALIVE_TIME_MS: 20 seconds
GRPC_ARG_KEEPALIVE_TIMEOUT_MS: 10 seconds
GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS: 1
GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS: 10 seconds
GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS: 20 seconds
GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA: 1
```

Setting `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` to 0 will cause GOAWAYs to occur, so it sounds like your theory was correct.

**Comment by RahulMitra** [comment] 2018-07-30 22:00
Happy to run any additional tests if that's useful. 

Also, here is the client and server code I've been using to test the streams, in case you'd like to investigate further on your own.

In my case, I'm working with a bi-directional stream called `SeProxyService` that sends `SeProxyMessage` back and forth:

```
service SeProxyService {
    rpc Connect(stream SeProxyMessage) returns (stream SeProxyMessage);
}
```

C++ Client:
```
using google::protobuf::Message;
using grpc::Channel;
using grpc::ChannelArguments;
using grpc::ClientContext;
using grpc::ClientReader;
using grpc::ClientReaderWriter;
using grpc::ClientWriter;
using grpc::Status;

#define DEFAULT_KEEPALIVE_TIME_SECONDS 10
#define DEFAULT_KEEPALIVE_TIMEOUT_SECONDS 10
#define DEFAULT_KEEPALIVE_PERMIT_WITHOUT_CALLS 1
#define DEFAULT_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_SECONDS 10
#define DEFAULT_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_SECONDS 20
#define DEFAULT_HTTP2_MAX_PINGS_WITHOUT_DATA 0

DEFINE_int32(keepalive_time_seconds,                DEFAULT_KEEPALIVE_TIME_SECONDS, "in seconds");
DEFINE_int32(keepalive_timeout_seconds,             DEFAULT_KEEPALIVE_TIMEOUT_SECONDS, "in seconds");
DEFINE_int32(keepalive_permit_without_calls,        DEFAULT_KEEPALIVE_PERMIT_WITHOUT_CALLS, "");
DEFINE_int32(min_recv_ping_interval_without_data,   DEFAULT_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_SECONDS, "in seconds");
DEFINE_int32(min_sent_ping_interval_without_data,   DEFAULT_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_SECONDS, "in seconds");
DEFINE_int32(max_pings_without_data,                DEFAULT_HTTP2_MAX_PINGS_WITHOUT_DATA, "");

int main(int argc, char *argv[]) {

    google::ParseCommandLineFlags(&argc, &argv, true);    
    
    std::string SE_RPC_PROXY_PORT = "5091";
    std::string G_CTRL_IP = "node1.controller.local";
    std::string target = G_CTRL_IP + ":" + SE_RPC_PROXY_PORT;
     
    std::cout << "GRPC_ARG_KEEPALIVE_TIME_MS: " << FLAGS_keepalive_time_seconds << " seconds" << endl;
    std::cout << "GRPC_ARG_KEEPALIVE_TIMEOUT_MS: " << FLAGS_keepalive_timeout_seconds << " seconds" << endl;
    std::cout << "GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS: " << FLAGS_keepalive_permit_without_calls << endl;
    std::cout << "GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS: " << FLAGS_min_recv_ping_interval_without_data << " seconds" << endl;
    std::cout << "GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS: " << FLAGS_min_sent_ping_interval_without_data << " seconds" << endl;
    std::cout << "GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA: " << FLAGS_max_pings_without_data << endl;
    
    int SECONDS = 1000;
    grpc::ChannelArguments ch_args;    
    ch_args.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, FLAGS_keepalive_time_seconds * SECONDS);
    ch_args.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, FLAGS_keepalive_timeout_seconds * SECONDS);
    ch_args.SetInt(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, FLAGS_keepalive_permit_without_calls);
    ch_args.SetInt(GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS, FLAGS_min_recv_ping_interval_without_data * SECONDS);
    ch_args.SetInt(GRPC_ARG_HTTP2_MIN_SENT_PING_INTERVAL_WITHOUT_DATA_MS, FLAGS_min_sent_ping_interval_without_data * SECONDS);
    ch_args.SetInt(GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA, FLAGS_max_pings_without_data);

    auto grpc_channel_ = grpc::CreateCustomChannel(target, grpc::InsecureChannelCredentials(), ch_args);
    //auto grpc_channel_ = grpc::CreateChannel(target, grpc::InsecureChannelCredentials());

    if (grpc_channel_ == nullptr) {
        std::cout << "ERROR: Failed to make GRPC Channel" << endl;
        return 0;                                   
    }
    std::cout << "created grpc_channel to target: " << target << endl;

    while (true) {

        // Create stream from stub
        ClientContext context;
        std::unique_ptr<SeProxyService::Stub> se_proxy_stub = SeProxyService::NewStub(grpc_channel_);
        std::shared_ptr<ClientReaderWriter<SeProxyMessage, SeProxyMessage> > stream(se_proxy_stub->Connect(&context));

        if (stream == nullptr) {
            std::cout << "ERROR: Stream did not connect, retrying in 5 seconds" << endl;                             
            sleep(5);
            continue;
        }

        std::cout << "Successfully connected stream. Listening on incoming messages" << endl;                             

        /* Listen on incoming messages */
        SeProxyMessage se_proxy_message;
        while (stream->Read(&se_proxy_message)) {
        }
        std::cout << "Stream broke. Re-connecting in 1 second" << endl;                             
        sleep(1);
    }
}
```

Invoke as such:
```
./<binary_name> --keepalive_time_seconds=20 --max_pings_without_data=1 <etc.>
```

Golang server:
```
func TestStreamServer(t *testing.T) {
	port := 5091

	// Defaults
	serverParamsTime := 10
	serverParamsTimeout := 10
	enforcementPolicyMinTime := 10

	// Pass other values for testing
	if os.Getenv("SERVER_PARAMS_TIME") != "" {
		serverParamsTime, _ = strconv.Atoi(os.Getenv("SERVER_PARAMS_TIME"))
	}
	if os.Getenv("SERVER_PARAMS_TIMEOUT") != "" {
		serverParamsTimeout, _ = strconv.Atoi(os.Getenv("SERVER_PARAMS_TIMEOUT"))
	}
	if os.Getenv("ENFORCEMENT_PARAMS_MINTIME") != "" {
		enforcementPolicyMinTime, _ = strconv.Atoi(os.Getenv("ENFORCEMENT_PARAMS_MINTIME"))
	}

	glog.Infof("keepalive.ServerParameters Time: %+v Seconds", serverParamsTime)
	glog.Infof("keepalive.ServerParameters Timeout: %+v Seconds", serverParamsTimeout)
	glog.Infof("keepalive.EnforcementPolicy MinTime: %+v Seconds", enforcementPolicyMinTime)

	grpcServer := grpc.NewServer(
		grpc.KeepaliveParams(
			keepalive.ServerParameters{
				Time:    (time.Duration(serverParamsTime) * time.Second),
				Timeout: (time.Duration(serverParamsTimeout) * time.Second),
			},
		),
		grpc.KeepaliveEnforcementPolicy(
			keepalive.EnforcementPolicy{
				MinTime:             (time.Duration(enforcementPolicyMinTime) * time.Second),
				PermitWithoutStream: true,
			},
		),
	)

	addr := fmt.Sprintf("localhost:%v", port)
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		glog.Errorf("[ServiceInitialize] ERROR: Failed to listen: %v", err)
	}
	seRpcProxy := &seRpcProxyTest{}
	aviproto.RegisterSeProxyServiceServer(grpcServer, seRpcProxy)

	if lis != nil {
		go grpcServer.Serve(lis)
	}

	// Main goroutine sits idle
	for {
		time.Sleep(time.Duration(60) * time.Second)
	}
}
```
Invoke as such:
```
SERVER_PARAMS_TIME=20 ENFORCEMENT_PARAMS_MINTIME=20 <etc.> ./<binary_name>
```

**Comment by dfawley** [comment] 2018-07-30 22:12
@RahulMitra thanks so much for the update and reproduction code!

Does this sound right, @yashykt?  The user is setting `PermitWithoutStream`, which means the grpc-go server doesn't consider a ping to be problematic unless it falls inside the `MinTime` window, regardless of data frames being sent.  Here is our logic that implements that check:

https://github.com/grpc/grpc-go/blob/8fbeaf87a68ad9f4e7eaf69d605d0a888277de40/internal/transport/http2_server.go#L686-L705

I wonder if this setting is just covering up the problem by disabling pings entirely.  Note that the client never sends data; I'm not sure if the server does in the test implementation.  When does the PINGS_WITHOUT_DATA setting allow the next ping?  Is it on sending data or receiving data or both?

**Comment by yashykt** [comment] 2018-07-31 00:31
@RahulMitra It would be easier if you just create a gist so that I have access to the entire code including the protos and the build files.
Luckily, I had similar code lying around, so I was quickly able to reproduce this.
@dfawley your intuition is right. C++ does not seem to be scaling this. The issue is that the updated keepalive_time is maintained locally as part of the transport struct but we create a new transport for each subchannel, which means that this updated value is now lost, unless we are somehow able to update the channel args from inside the http2 transport. This seems to be breaking layers and will need a bit of a design discussion. Let me get back to you on this.

**Comment by yashykt** [comment] 2018-08-01 15:53
Going to track this in https://github.com/grpc/grpc/issues/16210 instead since it is a grpc core issue

**Comment by dfawley** [comment] 2018-08-01 16:28
@yashykt thanks!  I'll close this one out, since I think the Go side is OK here.

**Closed by dfawley** 2018-08-01 16:28 UTC
Labels: Status: Requires Reporter Clarification, Type: Bug
