### ISSUE TITLE
Open up internal/transport.Err* for inspection

### ISSUE THREAD

**Issue by utrack** [grpc/grpc-go#3061] opened 2019-10-02 10:40 UTC
Open up [internal transport's errors](https://github.com/grpc/grpc-go/blob/master/internal/transport/transport.go#L743) for inspection in `StatsHandler`. Re #3060 

Right now they're reported as errors w/ code=`INTERNAL`, which makes it impossible to tell them from errors returned by handlers:
```
err=&status.statusError{
           Code:                 13,
           Message:              "transport: connection error: desc = \"transport is closing\"",
           Details:              nil,
           XXX_NoUnkeyedLiteral: struct {}{},
           XXX_unrecognized:     nil,
           XXX_sizecache:        0,
       }
```

### Use case(s) - what problem will this feature solve?
Differentiation between transport errors and handlers' errors in `StatsHandler`.

### Proposed Solutions
Either
- moving transport errors from `internal` - pollutes main module
- adding some sort of `grpc.IsTransportError()`
- creating a new subpackage for errors' inspection (w/ collection of all possible errors perhaps?)

### Alternatives Considered
Right now the only way to know if it's a transport error is an assert by text like this:
`err.Error() == "rpc error: code = Internal desc = transport: connection error: desc = \"transport is closing\""`

**Comment by menghanl** [comment] 2019-10-02 23:04
transport errors are implementation details. And even if the error is exported, what you eventually get is not the original error, but a status wrapper on top of that.

All status error caused by connection error should have code `unavailable`. Checking status code should be enough.

---

`internal` should not be returned with "transport is closing". Which gRPC version are you using? And how to reproduce this error?

**Closed** 2019-10-17 21:38 UTC
Labels: Status: Requires Reporter Clarification, Type: Feature
