### ISSUE TITLE
Use vendored dependencies

### ISSUE THREAD

**Issue by bobbytables** [grpc/grpc-go#666] opened 2016-05-05 17:38 UTC
Right now a lot of the dependencies for this package shift _a lot_. Protobufs, http2, etc. It might be worthwhile to take advantage of the `vendor` directory support added in Go 1.5.

It seems anytime we do a go get using the `grpc` package, something breaks because the latest version of the `http2` package is incompatible for what grpc was built for.

Thoughts?

**Comment by thinkerou** [comment] 2016-05-17 10:58
I think that I should use `Go vendor`, not use `godep` or other in order to reduce dependeny.

**Comment by dominikh** [comment] 2016-07-06 23:32
Libraries should not vendor their dependencies; vendoring is the responsibility of the application. You should vendor a suitable copy of grpc-go, as well as its dependencies.

When libraries start vendoring what happens is that a program ends up with multiple versions of the same library, or vendored types leaking into the public APIs.

**Comment by bluecmd** [comment] 2016-07-08 04:03
The problem is not the grpc-go library part, it's the protobuf compiler interface that should be vendored, and other utils that may or may not be included.

**Comment by fd** [comment] 2016-07-08 10:02
>  In this scenario we're trying to build a Go project that is otherwise vendored, but has chosen to not supply generated protobuf files.

This is considered bad practice as you lose reproducible builds by not including the generated `.go` files in your library package. A package that has generated code should always have the generated code committed along with the other code.

you should never have to do a  `go generate ./vendor/...`

**Comment by bluecmd** [comment] 2016-07-08 13:43
> This is considered bad practice as you lose reproducible builds by not including the generated .go files in your library package.

if your statement was the official statement form the gRPC team that "Indeed, we expected everyone to ship generated pb files" then I would be happy with that. This however I cannot find, and I actually remember the thread back in Februrary where this was discussed (https://groups.google.com/forum/#!activity/grpc-io/dLRtQJzOCQAJ) with no clear guidelines.

As long as gRPC+Protoc is vendored and you track which gRPC+Protoc version you're using to build it's reproducible. I don't see how this is different from YACC/LEX software that needs to generate their .c counterpart - or if you want to take it even further, any build environment bootstrapping golang or gcc.

**Comment by hsaliak** [comment] 2017-05-17 00:49
We are not considering vendoring at the moment in grpc-go at the moment, so I am going to close this issue. The issues debated here are widely known and acknowledged - the general problem of dependency management for the library does need solving. 
We will likely end up adopting any official guideline in this regard, but there are not any yet.

**Closed by hsaliak** 2017-05-17 00:49 UTC

**Comment by bluecmd** [comment] 2017-05-18 03:47
Why close the issue then? Can't it stay open in recognition of the needed work?
