### ISSUE TITLE
grpc: propagate error and http status to caller when received HTTP method is not POST

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#2881] opened 2019-06-24 23:00 UTC
It came up during discussion that grpc-go may not be verifying that the HTTP method is POST. grpc-go should fail RPCs if the method is anything but POST. While there is an experimental GET protocol (which isn't really making any progress toward stabilization), it is quite different and wouldn't be supported by grpc-go without explicit support.

**Comment by menghanl** [comment] 2021-05-04 17:14
fixed by #4241

**Comment by ejona86** [comment] 2021-05-10 19:54
Reopening because the fix doesn't communicate the failure to the remote appropriately.

**Comment by dfawley** [comment] 2021-05-11 17:34
What is the appropriate way to communicate the failure?

**Comment by ejona86** [comment] 2021-05-11 17:59
Java [right now](https://github.com/grpc/grpc-java/blob/dbc5786c30b051e771c62de5a204deb45d7cdffb/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L426-L430) responds with HTTP 405, INTERNAL gRPC status, and a text/plain response. HTTP 501 would also be appropriate, although earlier versions of HTTP required supporting GET+HEAD and so claimed 405 was more appropriate for those methods.

In no way do I claim Java's implementation is ideal. It was just _much_ better than what was there before.

**Comment by bdhess** [comment] 2022-02-04 14:27
Is there more context on why this change is needed?  It took me a long time to root cause why a package update to google.golang.org/grpc broke clients.

Turns out that gRPC-C++ has a ClientContext settings for [idempotency](https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/include/grpcpp/impl/codegen/client_context.h#L284) which causes the HTTP method to be PUT instead of POST.

I guess that setting is marked experimental -- is the experiment not moving forward?

**Comment by ejona86** [comment] 2022-02-04 16:06
@bdhess, why were you using PUT?

I'm surprised PUT is still there in C++. That feature died. It was to allow things like QUIC to do 0-RTT transmission of the RPC, which can be replayed. However, it was later determined that "idempotent" isn't the same as "safe to replay by an attacker" and so PUT was nerfed in QUIC and became no faster than POST.

The work was supplanted by GET work which is still 0-RTT, but I think that was recently stripped from C++ because it was incomplete, hadn't moved forward in years, and was a maintenance burden. I'm surprised PUT is still there, but it is probably because it has low maintenance cost. There's still some interest in GET, but adding the code back was seen to be better than maintaining it in limbo.

There was no GET/PUT testing with Go. That work was all focusing on mobile so Java/C++ were the only things impacted (and client-side-only in Java). It never got out of testing though; it wouldn't be considered production ready. PUT is simple enough it probably mostly worked, but the compatibility story is completely missing. I know GET server-side support was broken in C++ because the server didn't verify the HTTP method matched what was allowed by the method. That's probably less of a concern for PUT, but probably still a bad idea.

**Comment by bdhess** [comment] 2022-02-04 17:59
Ack, thanks for the explanation.  Our code was calling that setter in grpc::ClientContext mostly because it seemed like a not-unreasonable thing to mark idempotent operations as such -- not necessarily for a MITMer to replay, but for client side retry logic akin to the standard gRPC retry policy.  I'm not sure we ever noticed the 'experimental' comment until now.

**Comment by ejona86** [comment] 2022-02-04 19:31
@bdhess, makes sense. That's one of the half-baked things about it actually. Java, for example, also allows setting a method as idempotent (generally copied from the proto definition), but it _wouldn't_ trigger the PUT logic because it was unclear if the server supported PUT. Instead, it can just be used locally by interceptors and the like. The API really gives no indication that it could cause compatibility issues, and it should.

**Comment by zasweq** [comment] 2022-09-07 00:18
Fixed by #5364.

**Closed by zasweq** 2022-09-07 00:18 UTC
Labels: P2, Type: Bug, fixit
