### ISSUE TITLE
Enable Connectivity State API

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-go#1245] opened 2017-05-16 20:54 UTC
The Connectivity State API was introduced in https://github.com/grpc/grpc-go/pull/690 but at the time it was _temporarily disabled_.

Year later, the `WaitForStateChange` and `GetState()` are still [private](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L787).

What's the reason for that? Can we enable this functionality?

Is there any other way to listen on channel/client state changes? My use case is reestablishing stream connections after server reconnects and in order to do that I need to have some way of listening on reconnect event.

**Comment by dfawley** [comment] 2017-05-26 16:08
Those functions deal with addrConns, which are individual connections, not the ClientConn, which represents a connection to zero or more servers.  It sounds like you're interested in just knowing whether the ClientConn is valid?

Can you attempt to re-establish the stream even though the server is still down, but set non-fail-fast and a very long deadline?

**Comment by lukaszx0** [comment] 2017-05-26 22:32
Thanks, I'll have a look - this will probably work.

Regardless of workaround though, shouldn't this be exposed in `ClientConn` as part of cross-language spec: https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#channel-state-api ?

**Comment by dfawley** [comment] 2017-06-05 18:04
We are planning to implement the connectivity state API next quarter (by September).

**Comment by TheSalmonTapes** [comment] 2017-06-05 22:59
Thanks for the update!

**Comment by dfawley** [comment] 2017-06-30 21:50
Looks like there's a dupe of this.  #1208.

**Closed by dfawley** 2017-06-30 21:50 UTC
Labels: enhancement
