### ISSUE TITLE
possible deadlock in google.golang.org/grpc/transport.(*http2Client).controller

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#804] opened 2016-07-30 16:48 UTC
After moving to latest grpc-go, we are seeing a lot of failures in CI resulting from leaked goroutines.

https://github.com/cockroachdb/cockroach/issues/8133
https://github.com/cockroachdb/cockroach/issues/8135
https://github.com/cockroachdb/cockroach/issues/8146

**Comment by tamird** [comment] 2016-07-30 17:45
Possible related to #802.

**Comment by iamqizhao** [comment] 2016-07-30 18:09
I think so. it was merged. I close this one. Please reopen if it remains.

**Comment by tamird** [comment] 2016-07-30 18:14
No, we need to reopen this (and I can't). The failures we were seeing were on 5a547ed72c09faf4050739d54caea1d51f4d276d which did not include #799 at all.

**Comment by iamqizhao** [comment] 2016-07-30 18:18
anyway we can reproduce?

**Comment by tamird** [comment] 2016-07-30 18:19
I haven't been able to :(

I wrote up my attempts https://github.com/cockroachdb/cockroach/issues/8133#issuecomment-236373835.

**Comment by iamqizhao** [comment] 2016-07-30 19:01
I remember I saw something similar one or two times in the past 2 weeks in our testing suite. It seems only happen on traivs and I cannot reproduce locally. I am looking. Is it possible you sync to the latest code so that we can i) make sure it remains in the latest code and ii) debugging effort can be synchronized? Thank you. Sorry about all these troubles. We have made quite a few complex changes (e.g., goaway) recently for GA and they seem introduce some issues ...

**Comment by iamqizhao** [comment] 2016-07-30 19:03
BTW, I have run our test suite thousands of times locally and about ten times on travis but have not seen anything yet.

**Comment by tamird** [comment] 2016-07-30 19:08
Sure, https://github.com/cockroachdb/cockroach/pull/8150.

Our stress tests run nightly - I'll let you know what happens tomorrow night.

**Comment by tamird** [comment] 2016-07-30 21:02
I am able to reproduce this using grpc's tests using https://github.com/cockroachdb/stress!

```
go test google.golang.org/grpc//test -c && stress -maxfails 1 -stderr ./test.test -test.run TestServerGoAway
```

Reproduces in under 30 seconds both in go1.6.3 and go1.7rc3.

**Comment by iamqizhao** [comment] 2016-07-30 21:18
Thanks, it works! I will take a look tomorrow or Monday. Have a good weekend.

**Comment by iamqizhao** [comment] 2016-07-30 23:35
Yeah, I found the root cause and have a fix now. will give it another careful check and send out on Monday. Thanks again for your input.

**Comment by tamird** [comment] 2016-07-30 23:37
No problem. And all I ask in return is that you review
https://github.com/grpc/grpc-go/pull/796 :)

**Closed** 2016-08-01 20:26 UTC
