### ISSUE TITLE
Proto 3 Optional Support for protoc-gen-go-grpc

### ISSUE THREAD

**Issue by PFacheris** [grpc/grpc-go#3739] opened 2020-07-12 16:38 UTC
When attempting to try optional support w/ proto 3 as described at https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md, I'm met with the following error:

```
projects_test_proto3_optional.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-go-grpc hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--go-grpc_out:
```

**Comment by GarrettGutierrez1** [comment] 2020-07-15 19:33
Duplicate of #3629

**Closed** 2020-07-15 19:33 UTC
Labels: Type: Feature
