### ISSUE TITLE
exec.Command exit status 128

### ISSUE THREAD

**Issue by urko-b** [grpc/grpc-go#6046] opened 2023-02-22 11:32 UTC
### What version of gRPC are you using?
google.golang.org/grpc v1.52.0
google.golang.org/protobuf v1.28.1

### What version of Go are you using (`go version`)?
1.19

### What operating system (Linux, Windows, …) and version?
Debian GNU/Linux 11 (bullseye)
### What did you do?
I've build my application with `go build` command. Binary is created successful. From same directory where my `go` project is placed (example: /home/go/myproject) I run ./bin/mybinary. Everything is working fine.

I created a `unit-file` to run this application as service through `systemctl`. I was getting this error after run `systemctl start myservice` **exec.Command exit status 128**

I decided to try to go to `/home` and run manually my binary `/home/go/myproject/bin/mybinary`. I've got same error.
So It seems when I run my binary out of the root dir of the go project (/home/go/myproject) I'm getting exit status 128.

Could you please give me further instructions about how can I fix this problem? I can't extract more information about the error and is a bit annoying.

**EDIT:**
I've  created [this issue](https://superuser.com/questions/1769855/debian-unitfile-execstart-binary-error-but-manually-works) on superuser.com where you might get some additional details about the error.

### What did you expect to see?
Binary should be executed through any system path.

### What did you see instead?
Binary execution is raising `exec.Command exit status 128`

**Comment by urko-b** [comment] 2023-02-22 17:00
As a temporary patch what I've found as solution is to create a bash script and run it with `/usr/bin/bash` instead of calling directly binary itself:

I've posted detailed answer here:
https://superuser.com/a/1770147/1120220

**Comment by zasweq** [comment] 2023-02-22 18:40
Besides the fact that you say you have other Go applications and this one happens to use gRPC which errors, what else leads you to think this is a gRPC problem. Binaries can contain arbitrary amounts of layers on top of our library/are running on your specific Linux system, so what makes you think this problem is pinpointed to gRPC. A program exiting with an exit code does not give me enough information or specify why this is a gRPC problem.

**Comment by urko-b** [comment] 2023-02-22 18:53
If you take a look on the **[superuser](https://superuser.com/a/1770147/1120220)** post I've created. Is quite strange this behavior. I could achieve the goal just running binary manually.

I mentioned I've got other go applications like fiber REST APIs which I built using same execution script `go build ...` and I've started them from `unitfile` just setting binary absolute path on `execstart` parameter.

**Comment by zasweq** [comment] 2023-02-22 19:02
Right, can you please narrow down why you think this is a gRPC-Problem. go build is how you build go binaries yes, but this could have a ton of root causes.

**Comment by urko-b** [comment] 2023-02-22 19:05
As I mentioned. I've used all same packages in other `go` fiber REST API which I have up using same deploy method with `unitfile` through `systemctl` and It is working fine. As I told, I'll try to reproduce again the problem on a clean Debian environment on a VM when I have more time, maybe this or next week.

**Comment by zasweq** [comment] 2023-02-22 19:14
Ok, sounds good. Closing this for now. Once you narrow it down to a gRPC problem if so, please file another issue or comment on this one again. Thanks :).

**Closed by zasweq** 2023-02-22 19:14 UTC
Labels: Status: Requires Reporter Clarification, Type: Bug

**Comment by urko-b** [comment] 2023-03-09 08:56
ok I found the problem. Sorry it finally wasn't related with gRPC. It was something related to my environment variables configuration. I was missing one that was causing me bad execution.
