### ISSUE TITLE
Metadata with non-ASCII characters should panic

### ISSUE THREAD

**Issue by ishitatsuyuki** [grpc/grpc-go#1769] opened 2017-12-27 08:39 UTC
### What version of gRPC are you using?
master (no vendoring)
libprotoc 3.2.0

### What version of Go are you using (`go version`)?
go version go1.9.2 windows/amd64

### What did you do?
```
	header := metadata.Pairs("x-header-key", "ｕｎｉｃｏｄｅ")
	trailer := metadata.Pairs("x-trailer-key", "ｕｎｉｃｏｄｅ")
	grpc.SendHeader(ctx, header)
	grpc.SetTrailer(ctx, trailer)
```

### What did you expect to see?
This should panic because it violates the HTTP protocol.

### What did you see instead?
This didn't panic and sent non compliant response out.

**Comment by dfawley** [comment] 2018-01-04 23:58
Panicking should be avoided if at all possible.  `SetHeader` and `SendHeader` could return errors.  Unfortunately, `grpc`'s `ServerStream.SetTrailer` doesn't return an error.  In this case, one other option would be to make the transport force the stream to result in an error with an error message indicating that the server attempted to send malformed metadata.

**Comment by menghanl** [comment] 2018-06-13 21:34
Duplicate of #468

**Closed by menghanl** 2018-06-13 21:34 UTC
Labels: P2, Status: Duplicate, Type: Bug
