### ISSUE TITLE
examples/route_guide/client doesn't respect ProxyFromEnvironment 

### ISSUE THREAD

**Issue by ahmetb** [grpc/grpc-go#3943] opened 2020-10-08 23:07 UTC
### What version of gRPC are you using?

master = 5af6040

### What version of Go are you using (`go version`)?

go version go1.15.2 darwin/amd64

### What did you do?

- `git clone`
- `cd grpc-go/examples/route_guide`
- Run `go run ./server` in a window
- Start a transparent HTTP proxy [like this](https://github.com/elazarl/goproxy/tree/0581fc3aee2d07555835bed1a876aca196a4a511#a-taste-of-goproxy) on :8080
- Try `env HTTP_PROXY=:8080 go run client/client.go`

### What did you expect to see?

When HTTP_PROXY or HTTPS_PROXY env vars specified, example doesn't respect pick up and use these values in the default HTTP client used under the covers.

As a user, it's not clear to me how to make the underlying http.Transport do "ProxyFromEnvironment".

I think the default behavior of the clients should be to respect HTTP_PROXY [according to this comment claims](https://github.com/grpc/grpc-go/issues/2243#issuecomment-408459983).

My transparent proxy works just fine e.g. `curl -x localhost:8080 example.com` captures the HTTP traffic.

### What did you see instead?

`go run ./client` works fine.

`env HTTP_PROXY=:8080 go run client/client.go` also works fine BUT the traffic doesn't go through the proxy. 

Setting `HTTP_PROXY` to garbage value `:9999` seems to confirm this as it still works with that.

**Comment by menghanl** [comment] 2020-10-09 01:21
I remember I had problem setting proxy to localhost, that could be the reason. Can you try to get your real IP address and use that? E.g. `HTTP_PROXY=192.168.1.123:8080`

**Comment by ahmetb** [comment] 2020-10-09 03:13
That doesn't work either. Tried both IPv4 and IPv6 as well.  Since setting it to `HTTP_PROXY=8.8.8.8:80` (an unreachable address) continues to work,  I'm inclined to think it's not being picked up. :)

**Comment by ahmetb** [comment] 2020-10-15 04:03
Appreciate if anyone can explain why the DefaultTransport is not picked up in sample code or gRPC programs. This undocumented and hard to find.

**Comment by easwars** [comment] 2020-10-15 23:11
When the client calls `grpc.Dial()`, gRPC looks to see if requests on the about-to-be-created `ClientConn` should be proxied. It uses `http.ProxyFromEnvironment` to make that decision. Please see [here](https://github.com/grpc/grpc-go/blob/ea47aa91b3da3f71e0c079a4c806bdd529efcdf5/proxy.go#L50).

Now, if we look at what the `http` package does, it invokes the `httpproxy` package to fetch the proxyURL. Following this code path, we reach [here](https://github.com/golang/net/blob/4f7140c49acb4c7e276e0b67dea953d5344ae064/http/httpproxy/proxy.go#L183) where the `httpproxy` package explicitly decides that any requests to `localhost` and `loopback` IPs should not be proxied. 

This explains why your requests are not hitting the proxy (or failing when you set the environment variables to non-existent proxies). Basically, if the client is trying to talk to a server on a `localhost` or `loopback` IP, proxying will be disabled. Try running the server on a different machine, or try setting the server's listening address to the public IP of the machine and see if proxying works. HTH. 

I'm closing this as it looks like it is "working as intended" or at least "working as written". Please feel free to re-open if you still think this is a gRPC bug. Thanks.

**Closed by easwars** 2020-10-15 23:11 UTC
Labels: Type: Bug

**Comment by easwars** [comment] 2020-10-15 23:13
And this is clearly documented in `http.ProxyFromEnvironment`:

```
// As a special case, if req.URL.Host is "localhost" (with or without
// a port number), then a nil URL and nil error will be returned.
```

**Comment by menghanl** [comment] 2020-10-15 23:57
And now I think I remember the problem I had with proxy and localhost.

The solution I tried was to change the Dial target to real IP of the local machine, not to change the proxy address in the env variable.

**Comment by ahmetb** [comment] 2020-10-16 19:57
Ack thanks. Hopefully this issue serves as a knowledge base for anyone else stumbling upon it later.
