### ISSUE TITLE
Server error on client close.

### ISSUE THREAD

**Issue by HeinOldewageRetro** [grpc/grpc-go#1062] opened 2017-02-03 06:15 UTC
When running the helloworld example, the client executes successfully and without error.
The server gives an error :

    transport: http2Server.HandleStreams failed to read frame: read tcp [::1]:50051->[::1]:58520: wsarecv: An existing connection was forcibly closed by the remote host.

This only happens when the client shuts down.

This might be fixed by issue #460

**Comment by linjohn** [comment] 2017-04-12 11:29
Yes, and this seems only to happen under Windows. If I cross compile it to Linux it works without error.

**Comment by tamird** [comment] 2017-04-12 11:31
Probably related to https://go-review.googlesource.com/c/39490/.

**Comment by fho** [comment] 2017-06-28 16:31
@linjohn also happens on Linux when I establish a connection and then call `con.Close()`
` transport: http2Server.HandleStreams failed to read frame: read tcp [..]: read: connection reset by peer`

**Comment by MakMukhi** [comment] 2017-06-28 18:00
This is not a bug but a log spam: there's a [goroutine](https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L384) on the server that reads on the connection synchronously, when the connection breaks(con.Close()), this gorutine logs an error out. Now the connection breaking might be completely valid (like in this case), the goroutine logs it out anyway.
We have a [PR](https://github.com/grpc/grpc-go/pull/1340) that'll take care of this by adding verbosity levels to log.
I'm going to go ahead and close this issue since there're already several issues tracking the same thing. Please track the aforementioned PR for updates.

**Closed by MakMukhi** 2017-06-28 18:00 UTC
Labels: bug
