### ISSUE TITLE
Possible source of ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:

### ISSUE THREAD

**Issue by rackerWard** [grpc/grpc-go#6696] opened 2023-10-05 22:51 UTC
I may have found a source for this

cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
        cloud.google.com/go v0.26.0 (/home/xxx/go/pkg/mod/cloud.google.com/go@v0.26.0/compute/metadata)
        cloud.google.com/go/compute/metadata v0.2.3 (/home/xxx/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.3)

I followed my dependency graph `go mod graph` and found the following.

github.com/cncf/xds/go@v0.0.0-20230607035331-e9ce68804cb4 google.golang.org/grpc@v1.25.1
google.golang.org/grpc@v1.25.1 github.com/envoyproxy/go-control-plane@v0.9.0
github.com/envoyproxy/go-control-plane@v0.9.0 google.golang.org/grpc@v1.23.0
google.golang.org/grpc@v1.23.0 cloud.google.com/go@v0.26.0

The `github.com/cncf/xds/go` module references an older version of grpc whose dependencies end up resolving to the `cloud.google.com/go v0.26.0 ` which conflicts with the modules using `cloud.google.com/go/compute/metadata`

I also have noticed that `google.golang.org/grpc` references `github.com/cncf/xds/go` and it references `google.golang.org/grpc`

**Comment by dfawley** [comment] 2023-10-10 20:20
Can you provide a small project that fails to build with this error?  I've never seen anything like it before.

**Comment by djames-bloom** [comment] 2023-12-12 10:20
I have also been running into this issue for the last few months, with it causing both `go mod tidy` and builds to fail. We've replicated this behaviour on go 1.19 through 1.21, on local systems, fresh containers, and also in CI. 

As a workaround, we've been needing to explicitly update before running `go mod tidy` or building our services.

```sh
❯ go get cloud.google.com/go
go: upgraded cloud.google.com/go v0.26.0 => v0.111.0
```

---

Running it up the chain, it appears that, at least in our case, Open Telemetry's gRPC interceptor, referencing this package is the leading cause. This latest version of this package (v0.46.1) is using `google.golang.org/grpc@v1.59.0`

```sh
❯ go mod why cloud.google.com/go/compute/metadata
# cloud.google.com/go/compute/metadata
[Redacted internal packages]
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test
google.golang.org/grpc/interop
golang.org/x/oauth2/google
cloud.google.com/go/compute/metadata
```

---

Example of attempting to `go mod tidy` without the workaround applied

```sh
❯ go mod tidy
go: [Redacted internal package] imports
    [Redacted internal package] imports
    [Redacted internal package] imports
    go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc tested by
    go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.test imports
    google.golang.org/grpc/interop imports
    golang.org/x/oauth2/google imports
    cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
    cloud.google.com/go v0.26.0 (/[redacted]/.gopath/pkg/mod/cloud.google.com/go@v0.26.0/compute/metadata)
    cloud.google.com/go/compute/metadata v0.2.3 (/[redacted]/.gopath/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.3)
```

---

@dfawley I'll attempt to create a project that replicates this issue - in the meantime, please let me know if you'd prefer this to be moved across to a new issue seeing as this one has been marked stale/completed.

**Comment by dfawley** [comment] 2023-12-12 22:34
@djames-bloom - thanks, a reproduction would be very helpful!

**Comment by djames-bloom** [comment] 2023-12-15 12:35
Hey @dfawley quick update on this, through various rounds of testing I'm going to count this as a "false" positive.

Through some deep diving, I can fairly certainly attain that this issue is caused by the following:

- Pre `v0.100.x` the package `cloud.google.com/go` bundled all of the various packages into one place
- This was then split into individual packages, which causes the ambiguous import path
- If any projects you had built previously required, or still required due to now unmaintained package (e.g. [gRPC Prometheus](https://github.com/grpc-ecosystem/go-grpc-prometheus) it would cause go mod to maintain a pre-0.100 release of the go package in the mod cache

In our case, we were seeing this replication in local, test and CI as we heavily cache our container build steps, causing pre-v0.100.x releases to remain in the mod cache.

Spare from others running into the same issue, I believe it's safe to close off this issue as it does not directly pertain to the contents of this repo, instead over-eager false-flagging by `mod tidy` and `mod why` output, placing blame on this project.

 ---

**For users running into this issue** 

we've found reliably a two step solution to resolve the issue.

1. Purge your go modules cache with `go clean -modcache`
2. Add the following as a trailer to your `go.mod` file
```
replace cloud.google.com/go => cloud.google.com/go v0.100.2
```

Note: obviously using the latest version would be preferential, but this will set a minimum acceptable version to be used.

**Comment by dfawley** [comment] 2023-12-15 17:35
Sounds great, thanks!  I'll close this for now, and if others run into this and try the above, but still have issues, please let us know (file a new issue and reference this one if this becomes locked).

**Closed by dfawley** 2023-12-15 17:35 UTC
Labels: Status: Requires Reporter Clarification, Type: Bug
