### ISSUE TITLE
Stream Batching

### ISSUE THREAD

**Issue by kiro** [grpc/grpc-go#524] opened 2016-02-03 11:55 UTC
Hi, we noticed 6x throughput improvement if we stream 100 byte messages in a batch of 50 (e.g. one response message with repeated field) rather than streaming them one by one. So are there plans to add support for batching in the streaming implementation?

Thanks,
Kiril

**Comment by iamqizhao** [comment] 2016-02-03 19:21
This will be tricky because batching might enlarge latency. We have some minimal deliberate batching support in the code already. But how to enhance it to maximize throughput without hurting latency is complex and need more time. Performance would be one of our main focus next quarter.

**Comment by xiang90** [comment] 2016-02-03 19:36
@iamqizhao Are we open to add a Flush() method to stream to enable user controlled batching?

**Comment by iamqizhao** [comment] 2016-02-03 21:09
This would be tricky on the interaction with Flush decision on the transport layer.

**Comment by bradfitz** [comment] 2016-02-05 20:07
@iamqizhao, Go's http2 server does this aggregation automatically. It has a write scheduler that only flushes only when a packet is full or there's nothing else to send. So if we switch, I think this should get a lot easier to control. (or ideally: not control, if it just works)

**Comment by iamqizhao** [comment] 2016-02-09 19:37
@bradfitz , as I mentioned, the current grpc transport does this automatically too (may be different from what http2 does). The problem is that whether Flush knob should be exposed to users.

**Comment by sailat** [comment] 2017-03-03 22:39
We are working on batching requests this quarter to improve perf. Will update this thread with available date soon.

**Comment by hsaliak** [comment] 2017-05-17 01:19
@dfawley assigning to you to triage and make a decision on exposing the `Flush` knob to users.

**Comment by dfawley** [comment] 2017-06-30 21:44
We discussed this today at some length.  Without major API changes or hacks (i.e. passing a magic wrapper type to `stream.SendMsg`), there isn't much we can do here.  It does sound like a good idea, though, so I'll leave it open.

**Comment by MakMukhi** [comment] 2017-12-14 19:23
We changed out write mechanism to use a dedicated loop to write which essentially solves the batching problem.

**Closed by MakMukhi** 2017-12-14 19:23 UTC
Labels: Type: Feature, Type: Performance
