### ISSUE TITLE
Is there a hook for server when the connection lost from client

### ISSUE THREAD

**Issue by joseAndresGomezTovar** [grpc/grpc-go#1063] opened 2017-02-03 10:44 UTC
#297 
I have the same requirement, because:
- I want to run a DLL remotely
# Scenary:
- I have a main process and tow dlls
- one of these dll will be run using the gRPC server
- By making a new dll "gRPC client" that is loaded in the main process, I remotely connect the original "dll" with the main process

The gRPC server loads the "original dll" when the connection is established, and it downloads it when it breaks

thank you in advance

**Comment by hsaliak** [comment] 2017-05-17 19:01
I am going to close the issue because it refers to #297 which is closed.  @joseAndresGomezTovar please re-open with an example of how we can reproduce what you are seeing.

**Closed by hsaliak** 2017-05-17 19:01 UTC
