### ISSUE TITLE
ServeHTTP never sends trailers-only responses

### ISSUE THREAD

**Issue by banks** [grpc/grpc-go#2206] opened 2018-07-09 14:58 UTC
Firstly, I realise `ServeHTTP` is experimental so this is perhaps not unexpected. While trying to coax it to work with a real-life gRPC client and an existing HTTP service (still not clear why that case didn't work) I spent a while mislead by the fact that `ServeHTTP` doesn't handle errors as expected (even though it does work when requests are well-formed).

Full description/repro below. I tried to debug this and I suspect it is to do with the fact that `serverHandlerTransport.WriteStatus` flushes after `writeCommonHeaders` but then closes the transport before it's either flushed or closed the `ResponseWriter` with the actual Status values set. 

### What version of gRPC are you using?

master (40cd6b1)

### What version of Go are you using (`go version`)?

`go version go1.10.2 darwin/amd64`

### What operating system (Linux, Windows, …) and version?

OS X 10.13.5 (17F77)
`Darwin Evariste.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`

### What did you do?

See the [repro gist](https://gist.github.com/banks/e7915ea3933a2dea4e5708bf72723205) based on the greeter example code. Note that client and server need to be run in separate dirs as in the orignal example - gists don't support multiple directories. The modifications made are:

 - add flag to switch between `Serve` and `ServeHTTP` mode
 - setup TLS using locally generated certificates - they are self-signed and don't have the necessary domain names but this is irrelevant as I'm skipping verification in all clients.
 - note same TLS config used for both modes (required to force http.Server to support HTTP2 at all)
 - modify the greater_client in the same way to support TLS with `InsecureSkipVerify = true`

If I run the server in either mode, the greeter client works (so `ServeHTTP` does work on the happy path):

```
greeter_client$ go run main.go
2018/07/05 12:29:17 Greeting: Hello world
```

However If I try to curl the server with an invalid path and empty RPC payload the behaviour is different. To be clear I realise curl is not a good tool to work with Protobufs and that I'd never get a working RPC this way, but it is a useful tool to debug why or why not http2 upgrades are happening which is how I spotted this behaviour.

I couldn't reproduce with a real gRPC client that was calling a method that was not implemented by the server so it _may_ be just an edge case with my `curl` invocation doing something differently to how a valid client would. That would significantly limit the impact and priority of a fix, but the fact the behaviour differs between `Serve` and `ServeHTTP` leads me to believe it's a bug at least.

Using `Serve`:
```
$curl -v --header "Content-Type: application/grpc" -k -X POST https://127.0.0.1:50051
<snip>
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8fb2807000)
> POST / HTTP/2
> Host: 127.0.0.1:50051
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/grpc
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< content-type: application/grpc
< grpc-status: 8
< grpc-message: malformed method name: "/"
<
* Connection #0 to host 127.0.0.1 left intact
```

Using `ServeHTTP`:
```
<snip>
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd59180a400)
> POST / HTTP/2
> Host: 127.0.0.1:50051
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/grpc
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< content-type: application/grpc
< trailer: Grpc-Status
< trailer: Grpc-Message
< trailer: Grpc-Status-Details-Bin
<
* Connection #0 to host 127.0.0.1 left intact
```

Notice that the trailers are set but with no actual values.

### What did you expect to see?

The same error response for both Serving modes

### What did you see instead?

See above

As noted, the impact of this might be small enough that there is no immediate fix proposed but it seems like a bug so I hope this report is useful.

**Comment by mastersingh24** [comment] 2018-09-09 12:43
Out of curiosity, I ran looked through the code and ran a few experiments and things are actually a bit different than in the write up above.

There is definitely a difference in behavior between `Serve` and `ServeHTTP`, but what I think I found is that `Serve` actually writes out response headers (not trailers) and `ServeHTTP` actually does write trailers but for some reason a "Trailer" response header is actually written out as well.

`curl` does not actually support displaying trailers as far as I know, so I used `nghttp2` instead.

Here's the response snippet for `ServeHTTP`:

```
[  0.022] recv (stream_id=13) :status: 200
[  0.022] recv (stream_id=13) content-type: application/grpc
[  0.022] recv (stream_id=13) trailer: Grpc-Status
[  0.022] recv (stream_id=13) trailer: Grpc-Message
[  0.022] recv (stream_id=13) trailer: Grpc-Status-Details-Bin
[  0.022] recv HEADERS frame <length=60, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0)
          ; First response header
[  0.022] recv (stream_id=13) grpc-message: malformed method name: "/"
[  0.022] recv (stream_id=13) grpc-status: 8
[  0.022] recv HEADERS frame <length=44, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
          (padlen=0)
[  0.022] send GOAWAY frame <length=8, flags=0x00, stream_id=0>

```
 and here's the snippet for `Serve`:

[  0.027] recv (stream_id=13) :status: 200
[  0.027] recv (stream_id=13) content-type: application/grpc
[  0.027] recv (stream_id=13) grpc-status: 8
[  0.027] recv (stream_id=13) grpc-message: malformed method name: "/"
[  0.027] recv HEADERS frame <length=58, flags=0x05, stream_id=13>
          ; END_STREAM | END_HEADERS
          (padlen=0)
          ; First response header
[  0.027] send GOAWAY frame <length=8, flags=0x00, stream_id=0>

**Comment by dfawley** [comment] 2018-09-10 22:33
Thanks for the extra information @mastersingh24.  What seems to be happening is that, when there is an error, `ServeHTTP` is not sending a "trailers-only" response like `Serve`; instead it's sending headers and then trailers as separate HTTP HEADERS frames.  In the headers, it pre-declares some trailers (Grpc-Status/etc), and in the trailers is the RPC's status.  This is actually a perfectly valid way of responding to the request, but there is a small downside in that it prevents client-side retry support from working.

**Comment by mastersingh24** [comment] 2018-09-11 12:19
@dfawley  - Maybe someone smarter than me can pull it off, but as of right now I could not find any good way of getting Go's http2 implementation to send trailer only responses.  :(

**Comment by dfawley** [comment] 2018-09-11 16:13
It would be a little ugly, but I think instead of calling writeCommonHeaders here:

https://github.com/grpc/grpc-go/blob/46ee6abebf62241b49973422c42250327bb94169/internal/transport/handler_server.go#L198

we could just write the "Content-Type" header (if common headers haven't been written yet), and never call `Flush` here, which actually says it's done to force headers and trailers to be separated (which we don't want; maybe I'm missing something else?):

https://github.com/grpc/grpc-go/blob/46ee6abebf62241b49973422c42250327bb94169/internal/transport/handler_server.go#L200-L203

**Comment by mastersingh24** [comment] 2018-09-11 17:04
I tried that ...but it did not seem to work ... I'll try it again

**Comment by dfawley** [comment] 2019-03-28 16:17
I just discovered this is a dupe of #553.

**Closed by dfawley** 2019-03-28 16:17 UTC
Labels: P3, Status: Duplicate, Type: Bug
