### ISSUE TITLE
Does Reflection Care The Service Being Registered to Server Or Not

### ISSUE THREAD

**Issue by kudla** [grpc/grpc-go#6152] opened 2023-03-25 07:57 UTC
Using [grpcurl](https://github.com/fullstorydev/grpcurl) + [reflection.Register](https://github.com/grpc/grpc-go/blob/master/reflection/serverreflection.go#L66) it looks like `ListMethods` returns descriptions for any Service Descriptor being compiled into a server running binary regardless related implementation were being registered to the server instance it self or not.

Is it really true or I've just miss the real registration flow within my app somehow?

If it is true is there any options to extend / customize Reflection functionality to provide only registered Service Methods only?

Thx.

**Comment by arvindbr8** [comment] 2023-03-28 22:29
Hi @kudla,

This does not seem like the expected behavior of the reflection server. It is only supposed to list only the Services that are registered to that reflection server. Could you give us a way to reproduce this issue somehow?

**Comment by kudla** [comment] 2023-04-09 19:25
I'v tested on a very basic clean setup it is reproduced as well

Reproduction repo [grpc-non-added-reflection](https://github.com/kudla/grpc-non-added-reflection)

Once definitions are imported into a server code regardless it was added as a Service to the server instance the Methods definitions are available for Server reflection reflection
For provided repo
```sh
go run .
```
```sh
2023/04/09 22:18:22 Listen on 3333 port with imported service desc {Test <nil> [{Method 0x13ba4e0}] [] protos/test.proto}

```
```sh
grpcurl --plaintext 127.0.0.1:3333 list
```
Outputs reflection service only
```
grpc.reflection.v1alpha.ServerReflection
```
Yet listing methods specifically for the imported Service 
```sh
grpcurl --plaintext 127.0.0.1:3333 list Test
```
describes it methods anyway
```sh
Test.Method
```

**Comment by arvindbr8** [comment] 2023-04-21 17:13
Thanks for the repo. Im able to repo the same. Let me take a look at what the expected behavior when the service name is passed on as a parameter to the function.

**Comment by arvindbr8** [comment] 2023-04-25 23:05
It seems to be the expected behavior. calling `list` on the reflection server only shows the services that are registered on the server. However the `list` on a service or method uses a file descriptor on the proto file for lookup. 

Closing the issue. Feel free to re-open if you think this is still unanswered.

**Closed by arvindbr8** 2023-04-25 23:05 UTC
Labels: Type: Question
