### ISSUE TITLE
PickerWrapper is blocking for 5 seconds, then passing along request successfully

### ISSUE THREAD

**Issue by tzusman** [grpc/grpc-go#3364] opened 2020-02-05 21:29 UTC
### What version of gRPC are you using?
1.27.0

### What version of Go are you using (`go version`)?
1.13.4 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Mac Catalina 10.15.1

### What did you do?
I wrote a test case which tests a very basic interaction between a client and server.  There is practically no processing occurring in the server handler to ensure that this issue isn't caused by my code.  I'm using TLS and RPCCredentials, although removing them don't effect the delay described below.

### What did you expect to see?
I expect a success or failure in my test case nearly immediately since I've emptied the server handler to include minimal processing.

### What did you see instead?
The test case takes almost exactly 5 seconds * number of client gRPC calls.  I've identified that [picker_wrapper.go#152](https://github.com/grpc/grpc-go/blob/master/picker_wrapper.go#L152) is taking exactly 5 seconds to perform the select statement.  After 5 seconds, my request is sent to the server successfully, with a valid response.

**Comment by dfawley** [comment] 2020-02-05 23:26
Do you have a reproduction test case that we can look at to see exactly what you're doing when this is encountered (ideally in a github repo or a gist)?

**Comment by tzusman** [comment] 2020-02-05 23:57
@dfawley I'll put together a simplified test case.  In the meantime, do you have any ideas on what could be the culprit?

**Comment by dfawley** [comment] 2020-02-06 02:20
No, that sounds unusual.  What load balancer are you using?

**Comment by tzusman** [comment] 2020-02-06 02:37
No load balancer, simply running the server locally and hitting it with my test case.

**Comment by dfawley** [comment] 2020-02-07 00:06
This is very unusual, then.  This select only unblocks (without an error) after the load balancer updates its picker.  For pick_first (the default), this will happen when the connectivity state of the client changes - e.g. your connection dies and comes back.

You should also try turning on logging to see what's happening: https://github.com/grpc/grpc-go#how-to-turn-on-logging

**Comment by tzusman** [comment] 2020-02-07 00:09
My co-worker figured out that this problem only occurs when running the server and client locally.  When the gRPC server is hosted on a remote server, the speed is as expected.  I'm now looking into how to get around this for local testing purposes.  If you have any suggestions, that would be great, otherwise I'll update this issue with the solution when I find it.

**Comment by dfawley** [comment] 2020-02-07 00:23
@tzusman we run with localhost all the time (see: 90% of our tests) and have never seen anything like this.  The logs may be helpful here.

**Comment by tzusman** [comment] 2020-02-07 00:41
Client:
```
INFO: 2020/02/06 17:40:05 parsed scheme: ""
INFO: 2020/02/06 17:40:05 scheme "" not registered, fallback to default scheme
INFO: 2020/02/06 17:40:05 ccResolverWrapper: sending update to cc: {[{my.local:50051  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2020/02/06 17:40:05 ClientConn switching balancer to "pick_first"
INFO: 2020/02/06 17:40:05 blockingPicker: the picked transport is not ready, loop back to repick
INFO: 2020/02/06 17:40:05 pickfirstBalancer: HandleSubConnStateChange: 0xc000123950, {CONNECTING <nil>}
INFO: 2020/02/06 17:40:10 pickfirstBalancer: HandleSubConnStateChange: 0xc000123950, {READY <nil>}
```

Server:
```
2020/02/06 17:40:10 stderr: INFO: 2020/02/06 17:40:10 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Comment by dfawley** [comment] 2020-02-07 16:44
If there are more log lines around here to show this repeating and other connection activity, it might be helpful.  What I can see, looking at the timestamps, that it's taking 5 seconds to connect:
```
INFO: 2020/02/06 17:40:05 pickfirstBalancer: HandleSubConnStateChange: 0xc000123950, {CONNECTING <nil>}
INFO: 2020/02/06 17:40:10 pickfirstBalancer: HandleSubConnStateChange: 0xc000123950, {READY <nil>}
```
And that someone (client or server or proxy??) is closing the connection almost immediately after the connection is established:
```
2020/02/06 17:40:10 stderr: INFO: 2020/02/06 17:40:10 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```
But from the information that is here, I can't see why it's taking 5 seconds to connect or why the connection is being closed at 17:40:10.

How long does a bare `net.Dial("my.local:50051")` take for you with this configuration?

**Comment by tzusman** [comment] 2020-02-07 18:15
> If there are more log lines around here

I'm setting `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info` and the logging above is all that's reported.  

> And that someone (client or server or proxy??) is closing the connection almost immediately after the connection is established:

This is because I've gutted the test case to isolate the issue.  Once the client request is made, the server immediately replies and the test is over.

> How long does a bare net.Dial("my.local:50051") take for you with this configuration?

Looks like we're getting somewhere.  This test case passes, but takes 5.01s.
```
func TestConnection(t *testing.T) {
	hostAndPort := fmt.Sprintf("%s:%s", os.Getenv("GRPC_HOST"), os.Getenv("GRPC_PORT"))
	_, err := net.Dial("tcp", hostAndPort)
	if err != nil {
		t.Fatalf("Error creating connection: %s", err.Error())
	}
}
```

**Comment by tzusman** [comment] 2020-02-12 21:54
@dfawley Little update for you while I'm debugging this.  If I connect to `localhost:50051`, it's immediate.  If I connect to `my.local` which has an entry in `/etc/hosts` to point to `127.0.0.1`, I get the 5 second delay.  It looks like a congested socket issue, or something along those lines, so I'm exploring that but I figured I'd share in case you have any ideas.

**Comment by dfawley** [comment] 2020-02-12 22:38
Sorry, I don't have any ideas about this, but it does sound unusual.  I will close this issue since the delay is also appearing in your bare `net.Dial`, meaning it is not a problem with grpc-go.  Thanks for filing the issue.

**Closed by dfawley** 2020-02-12 22:38 UTC
Labels: Status: Requires Reporter Clarification, Type: Bug
