### ISSUE TITLE
gRPC connection closing with unexpected EOF on high-latency connections

### ISSUE THREAD

**Issue by brianneville** [grpc/grpc-go#5358] opened 2022-05-16 20:16 UTC
### What version of gRPC are you using?
1.46.2

### What version of Go are you using (`go version`)?
go version go1.18 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Client is running MacOs:
  ProductName: macOS
  ProductVersion: 11.6
  BuildVersion: 20G165

Server is running Linux (CentOS 7)

### What did you do?

Note: I have posted a small repo that can be used to reproduce this bug, please check it out here:
[https://github.com/brianneville/grpcbug](https://github.com/brianneville/grpcbug)

-------

For high-latency connections, I noticed that RPCs were having their connection terminated with an internal error: 
`code = Internal desc = unexpected EOF`

This hits on both unary and streaming RPCs, and the ease with which this can be reproduced seems to vary with the client-server latency.
For high-latency connections (such 150ms ping), this error hits pretty much every time an RPC is called.
For low-latency connections (<2ms ping) this error is much more infrequent, and hundreds of thousands of messages may be streamed over this connection before the error is hit even once.

I did a bit of digging through the grpc library code, and found two ways that the error can be prevented:

#### 1.  Client side - configure window sizes
The error can be prevented from the client side by disabling the dynamic window and BDP estimation for flow control when dialing the grpc server. 
That is, setting the DialOptions on the client side to use:
```
    opts := []grpc.DialOption{
       grpc.WithInitialWindowSize(largerWindowSize),
       grpc.WithInitialConnWindowSize(largerWindowSize),
    }
```
Where both: 
 - `largerWindowSize` is greater than 65535 (so that dynamic window/flow estimation is turned off)
 - `largerWindowSize` is greater than the size of the largest RPC response messages (with a bit of overhead for some reason).

#### 2.  Server-side - delay ending the stream
The error can be prevented by delaying the calls that write the `StatusOk` into the transport. Specifically, if the END_STREAM header is delayed from being put into the `controlBuf` at [`google.golang.org/grpc/internal/transport/http2_server.go#finishStream`](https://github.com/grpc/grpc-go/blob/db79903af928ca8307700d83123a7702881c4e3c/internal/transport/http2_server.go#L1269). 
That is, you can make any of the following changes to `*http2Server.finishStream`, and the error will not be present:
```
    time.Sleep(1 * time.Second) // <-- sleeping before put = EOF error is prevented
    t.controlBuf.put(hdr)
```
or   
```
    go func() {         // <-- allowing finishStream to progress and sleep before put = EOF error is prevented
      time.Sleep(1 * time.Second)
      t.controlBuf.put(hdr)
    }()
```

When the `t.controlBuf.put(hdr)` line is delayed in this way, the RPC is allowed to complete normally, and the client will see the response as intended.

Note if you add the sleep after the `t.controlBuf.put(hdr)`, then the error will still be present (i.e. delaying the finishStream function is not what causes the error to be prevented)
```
    t.controlBuf.put(hdr)
    time.Sleep(1 * time.Second) // <-- sleeping after put = EOF error still occurs 
```

Would anyone know what might be going on here, or be able to give me some insight/advice for continuing to debug this issue?

### What did you expect to see?
Connection latency does not affect RPCs

### What did you see instead?
High-latency connection (such as ~150ms ping) reliably hit the error `code = Internal desc = unexpected EOF`

**Comment by zasweq** [comment] 2022-05-25 22:11
Hello, thank you for bringing up this issue/potential bug. In the current state, the team is unable to reproduce this. This requires pinging a remote peer running Centos 7, configured for a high ping. Could you please try reproducing this on the same machine, or even better, the same binary. grpc-go provides a latency package (https://pkg.go.dev/google.golang.org/grpc/benchmark/latency) that provides a way to inject real world latency into network connections. Reproducing in this way would a. Let the team reproduce it ourselves, and b. Get rid of all the other variables that may have caused this bug, and narrow the system under question down to our grpc code and the tcp stack it runs on top of.

**Comment by brianneville** [comment] 2022-06-06 15:27
Hi,

I wrote a test using the latency package as you described, but unfortunately as of yet I can't seem to reproduce the bug with this test. 
I wrote the test using the same RPC that I have been using to trigger the bug - https://github.com/brianneville/grpcbug
This test (at the time of this comment) is available here: https://github.com/brianneville/grpc-go/commit/e1ce0e5f2b19a4680ee1b4c6735316bc6bcf15f8 

I also recorded some debug logs showing the case where the bug hits in contrast to the case where it does not hit.
https://github.com/brianneville/grpcbug/tree/master/logs 
It's interesting that the bug only seems to hit when the server is on the remote (Centos) machine - hosting the server on my local (Mac) machine and attempting the RPC does not produce this EOF error. 

Something that may be relevant here is that the remote machine is very powerful relative to the local machine. 
I wonder whether this would allow the remote machine to experience some unanticipated interleaving of goroutines  (reading/writing) that could contribute to the error along with the high ping.

**Comment by dfawley** [comment] 2022-06-06 16:57
My worry is that there's something else in the system impacting it like a firewall or proxy.  It might be helpful to inspect the traffic with something like wireshark.

**Comment by brianneville** [comment] 2022-06-18 20:53
Hi,

The Centos remote machine is behind a VPN, although it's worth noting that this issue can be hit even when the client is on the same VPN (it's just a lot less frequent, presumably because the network connection is better)

Other points of note regarding the architecture(s) required to reproduce this issue:
The issue is reproducible when running the https://github.com/brianneville/grpcbug server on a Debian machine (tested with a Debian container on the Centos remote).
It is also reproducible when the client is either a Mac or Ubuntu machine.

**Comment by zasweq** [comment] 2022-06-29 23:51
Thanks for providing a smaller test case that reproduces the error seen in TestListResources. I was able to reproduce this error locally. Looking into it further now, interesting that it's also fixed with the window-size workaround. However, the orthogonal issue this issue was originally filed about is still too much for the team to reproduce (with the requirements of the machine the server is running on).

**Comment by zasweq** [comment] 2022-07-13 15:58
Yeah, thank you so much for finding this issue! Huge correctness issue within our repository, glad it got caught/fixed :). Weird that it didn't come up sooner.

**Comment by brianneville** [comment] 2022-08-02 15:39
Hi,

Really sorry to resurrect this thread again but the issue still seems to persist.  
That is to say, following the original instructions to reproduce this error (seen in https://github.com/brianneville/grpcbug#readme), still leads to an EOF, even when using the version of grpc-go which has https://github.com/grpc/grpc-go/pull/5494 in it. 

This #5494 did however fix the issue reproduced with the test https://github.com/brianneville/grpcbug/blob/master/related/teleport_test.go, but it looks like this issue just coincidentally shared an identical symptom and workaround.

Can you give me any advice on how to proceed with debugging this? 
You mention that it can't be reproduced on your hardware/setup, but is there anything that you would like me to try on my setup which might help to better understand what could be going on here?

**Comment by zasweq** [comment] 2022-08-02 18:03
Hey, sorry to see that this still persists. My biggest recommendation is to throw some logs around the http2_client and try and figure out what is triggering the EOF, similar to how we derived that new streams weren't getting the correct flow control number for the root cause of the failure for the teleport tests.

**Comment by hexfusion** [comment] 2022-08-09 10:30
@zasweq  curious if we think it could be related to this bug in net/http2? Could you help drive priority? This is causes huge problems for us in production with golang 1.18.

[1] https://github.com/grpc/grpc-go/issues/5358

**Comment by hexfusion** [comment] 2022-08-09 13:14
> Hi,
> 
> Really sorry to resurrect this thread again but the issue still seems to persist. That is to say, following the original instructions to reproduce this error (seen in https://github.com/brianneville/grpcbug#readme), still leads to an EOF, even when using the version of grpc-go which has #5494 in it.
> 
> This #5494 did however fix the issue reproduced with the test https://github.com/brianneville/grpcbug/blob/master/related/teleport_test.go, but it looks like this issue just coincidentally shared an identical symptom and workaround.
> 
> Can you give me any advice on how to proceed with debugging this? You mention that it can't be reproduced on your hardware/setup, but is there anything that you would like me to try on my setup which might help to better understand what could be going on here?

@brianneville were you using go 1.18? if yes we are also trying to see if this could be a possible regression go 1.17 -> 1.18

**Comment by dfawley** [comment] 2022-08-09 15:04
> @zasweq curious if we think it could be related to this bug in net/http2[1]? Could you help drive priority? This is causing huge problems for us in production with golang 1.18.

Unlikely, since grpc-go uses its own HTTP server implementation, and just the framer part of the net/http2 library.  But your link to the net/http2 issue is a link back to _this_ issue, so I can't see what you are referencing.

**Comment by zmb3** [comment] 2022-08-09 15:24
Anecdotal evidence only, but I don't recall seeing these failures prior to our Go 1.18 upgrade..

**Comment by hexfusion** [comment] 2022-08-09 17:55
To add a little more context. We are seeing this error with

```
rpc error: code = Internal desc = unexpected EOF"
```

client 
```
grpc.WithDefaultCallOptions(
  grpc.MaxCallRecvMsgSize(math.MaxInt),
  grpc.MaxCallSendMsgSize(math.MaxInt),
)
```

server
```
[]grpc.ServerOption{
  grpc.MaxRecvMsgSize(math.MaxInt),
  grpc.MaxSendMsgSize(math.MaxInt),
}
```

**Comment by brianneville** [comment] 2022-08-09 18:26
I compiled the server and client for the repo that reproduces this bug (https://github.com/brianneville/grpcbug) using go1.17.6 and the issue is still present, so I'd be hesitant to say that https://github.com/golang/go/issues/53253 is at fault here.

Jus to explore further though @hexfusion could you try appending the following DialOptions to the client?
```go
var opts []grpc.DialOption

// add any other DialOptions...

const maxWindowSize int32 = (1 << 20) * 16
opts = append(opts,
    grpc.WithInitialWindowSize(maxWindowSize),
    grpc.WithInitialConnWindowSize(maxWindowSize),
)
```
These DialOptions are a workaround for this bug (https://github.com/grpc/grpc-go/issues/5358) so it would be interesting to see if they have any effect in your case.

**Comment by hexfusion** [comment] 2022-08-09 18:33
Do you think that it would help even if in the case that we are setting Max to `math.MaxInt` as per above?

**Comment by brianneville** [comment] 2022-08-09 19:02
The options  `grpc.WithInitialWindowSize` and `grpc.WithInitialConnWindowSize` options are independent of the `grpc.MaxCallRecvMsgSize` and `grpc.MaxCallSendMsgSize` options. You can combine these options if you wish (I'd say try it, because I'm curious to see if the workaround has any effect in your case).

Setting  `grpc.WithInitialWindowSize` and `grpc.WithInitialConnWindowSize` will disable BDP and manually force the window size used to whatever value you provide it.
By comparison `grpc.MaxCallRecvMsgSize` and `grpc.MaxCallSendMsgSize` are for only setting the maximum size of the overall message that can be received/sent (with this message being sent in multiple data frames using a dynamic window size unless BDP is disabled).

**Comment by hexfusion** [comment] 2022-08-09 19:08
One more bit of context we see this right after `GOAWAY` from `MaxAge` . In a heavy traffic application. Generally speaking we are looking at about ~35000/TPS and the issue reproduces over a 48 hour window. The logs right before 

```
2022/08/06 01:54:20 INFO: [transport] transport: error closing conn during Close: close tcp 127.0.0.1:44067->127.0.0.1:51234: use of closed network connection
2022/08/06 01:54:20 WARNING: [transport] transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:44067->127.0.0.1:51234: use of closed network connection
2022/08/06 01:54:20 ERROR: [transport] transport: loopyWriter.run returning. Err: transport: Connection closing
2022/08/06 01:54:20 INFO: [core] [Channel #4] Channel Connectivity change to CONNECTING
2022/08/06 01:54:20 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc00053f330, {CONNECTING <nil>}
2022/08/06 01:54:20 INFO: [core] [Channel #4 SubChannel #5] Subchannel picks a new address "127.0.0.1:44067" to connect
2022/08/06 01:54:20 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to CONNECTING
2022/08/06 01:54:20 INFO: [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2022/08/06 01:54:20 INFO: [core] [Channel #4] Channel Connectivity change to IDLE
2022/08/06 01:54:20 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc00053f330, {IDLE <nil>}
2022/08/06 01:54:20 INFO: [core] [Channel #4 SubChannel #5] Subchannel Connectivity change to IDLE
```

**Comment by dfawley** [comment] 2022-08-09 20:47
If the connection is lost in the middle of an RPC then it's expected to get RPC failures.

You could use a `MaxAgeGrace` setting to help work around that issue when it's caused by `MaxAge` connection termination from the server.

**Comment by hexfusion** [comment] 2022-08-09 21:00
Thanks for the reply we currently have `MaxAgeGrace` set to `math.MaxInt64` to circumvent forceful closure of the stream. The result of those force closures was observed as.

```
rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR
```
After we bumped `MaxAgeGrace` we now see `rpc error: code = Internal desc = unexpected EOF`

**Comment by dfawley** [comment] 2022-08-16 17:51
How long after the initial GOAWAY are you seeing those EOF errors?  Are you still pretty sure it's related?  Does it still only reproduce every ~48 hours.

**Comment by hexfusion** [comment] 2022-08-16 19:42
`unexpected EOF` is right after `GOAWAY` which made me feel like it was a possible issue with transparent retry but have not proved it. It ranges between 48 -> 36 hours. Also FTR it was reproduced on go 1,17 which at this point is not that surprising but just in case folks see this later.

**Comment by hexfusion** [comment] 2022-08-16 19:49
I will create a new issue for this but the whole reason we are using `ServerMaxConnectionAge` is because we would overflow the stream id every now and then. `invalid stream ID`. So maybe its related.

**Comment by dfawley** [comment] 2022-08-16 20:10
> I will create a new issue for this but the whole reason we are using ServerMaxConnectionAge is because we would overflow the stream id every now and then. invalid stream ID. So maybe its related.

Interesting.  Apparently gRPC-Java will automatically reconnect when stream IDs are 50% exhausted.  We don't do that in gRPC-Go, but it would be a good idea.

**Comment by dfawley** [comment] 2022-08-16 21:11
@brianneville

> The error can be prevented by delaying the calls that write the StatusOk into the transport. Specifically, if the END_STREAM header is delayed from being put into the controlBuf at [google.golang.org/grpc/internal/transport/http2_server.go#finishStream](https://github.com/grpc/grpc-go/blob/db79903af928ca8307700d83123a7702881c4e3c/internal/transport/http2_server.go#L1269).
That is, you can make any of the following changes to *http2Server.finishStream, and the error will not be present:

Is this streaming RPCs, unary RPCs, or both?  If streaming, is it possible you are returning from your handler while another goroutine is attempting to write to the stream?

Are you using any keepalive settings, by any chance?

**Comment by brianneville** [comment] 2022-09-03 13:57
> Is this streaming RPCs, unary RPCs, or both?

That workaround (delaying ending the stream) works for both streaming and unary RPCs. 

>  If streaming, is it possible you are returning from your handler while another goroutine is attempting to write to the stream?

The EOF appears when there is just one streaming RPC running, i.e. one client streaming to one server, without any other clients streaming at the same time. If there are concurrency issues between writing and closing, then they're happening in some layer below the service (gRPC layer or lower).

>Are you using any keepalive settings, by any chance?

 https://github.com/brianneville/grpcbug doesn't use keepalive settings, but for the original program where this issue was observed (which the grpcbug repo is minimally reproducing) yes, the following keepalive settings being used: 
 ```go
 
 grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{MinTime: time.Second}),
grpc.KeepaliveParams(keepalive.ServerParameters{Time: 10 * time.Minute})
 ```

**Comment by ysoftman** [comment] 2023-02-11 16:15
I also have the same EOF message `rpc error: code = Internal desc = unexpected EOF` in etcdctl

When I use 'get' command in etcdctl on mac, It always outputs 'unexpected  EOF' . (ping endpoit: 15ms)
But it's OK for another Linux client (ping endpoint: < 2ms) or short results like (etcdctl get --prefix "/blabla" --limit 100)

I modified etcdctl source like below and I got all results.
https://github.com/etcd-io/etcd/blob/87e271701b3449c35d9ef41f855c7792488773ce/client/v3/client.go#L285
opts := append(dopts, grpc.WithResolvers(c.resolver), grpc.WithInitialWindowSize(1_000_000), grpc.WithInitialConnWindowSize(1_000_000))

**Comment by vimt** [comment] 2023-05-24 06:54
I recently encountered the same issue. The conclusion was that when communicating between the office network and the development environment network within my company, there is an "Man-in-the-middle" that identifies and forwards communication content. In a specific scenario, the "Man-in-the-middle" failed to forward a segment of the HTTP2 frame, resulting in the `unexpected EOF` error.

Here's how I discovered the issue:

I started a grpc client on the office network and a grp server on the development environment. When the server returned content with a length greater than 65535, there was a chance of getting the `unexpected EOF` error.

After capturing and comparing packets on both the client and server sides, I found that the packets on both sides could not be matched one-to-one, and some packet contents were modified. In the request that caused the `unexpected EOF` error, the server sent 5 DATA frames, but the client only received 4.

Other findings:

- `grpc.WithInitialWindowSize` to a value greater than the size of the body returned by the server will not result in the unexpected EOF error.
- grpc python client does not result in `unexpected EOF` error.

Therefore, this is not a grpc bug. If you need more detailed information, such as packet capture files, please let me know, and I will organize and share.

**Comment by FZambia** [comment] 2023-06-27 14:19
We also came across this issue in our organization. Reproduced only in local environment when connecting to the remote server behind vpn. Most probably there are more proxies on the way which I do not know about. Setting larger settings for window sizes as suggested above helped. Interesting thing - it never works with grpc-go client until tuning those options. But it works when sending request from Postman (though not always, sometimes Postman shows empty response with status ok) - possibly it has bigger defaults in its underlying client or not using some smart algorithms, hard to say.

**Comment by dfawley** [comment] 2023-10-17 16:22
One thing we suspect now is that the server might not be setting the linger socket option (need to check on this), which could lead to this kind of behavior if there is any TCP error after the server finishes writing the RPC data and closes the connection.

**Closed** 2024-02-12 16:38 UTC
Labels: P0, Type: Bug

**Comment by dfawley** [comment] 2024-02-12 16:49
Thank you to @s-matyukevich for figuring out what was going on here and sending an initial fix!
