### ISSUE TITLE
[question] Is it possible to dynamically change the type of service response?

### ISSUE THREAD

**Issue by tuhao1020** [grpc/grpc-go#4490] opened 2021-05-26 07:37 UTC
```proto
message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string msg = 1;
}

message UniResponse {
  int32 code = 1;
  string message = 2;
  optional google.protobuf.Any data = 3;
}

service HelloService {
  rpc Greet(HelloRequest) returns (HelloResponse) {}
}
```
as the code above, `Greet` returns `HelloResponse`， I want all the service returns a type like `UniResponse` without midify the proto file, the `UniResponse` will wrap oringal response data into its data field ,  then success response and error response can keep the same structure. 

```go
func UnaryServerInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	m, err := handler(ctx, req)

        // wrap oringal response
	x := &pb.UniResponse{
		Code: 1001,
                Message: "",
		Data:  m,
	}
	return x, err
}
```
 I have tried server side interceptor，but it doesn't work. Are there
other ways to do this?

**Comment by menghanl** [comment] 2021-06-01 22:15
No, type safety is an advantage of using proto, it's working by design.

The error code and error messages can be sent via RPC status, just return an error built using: https://pkg.go.dev/google.golang.org/grpc/status#Errorf

The status also supports sending more data if you need:
https://github.com/grpc/grpc-go/blob/master/examples/features/errors/server/main.go#L54

Closing this issue now. Please reply if you have further questions.

**Closed by menghanl** 2021-06-01 22:15 UTC
Labels: Type: Question
