### ISSUE TITLE
[Question] About Streaming API Message Usage

### ISSUE THREAD

**Issue by fuweid** [grpc/grpc-go#5857] opened 2022-12-12 04:02 UTC
It is asking for best practise about how to use streaming API's message. :) 

ETCD provides streaming API to transport the snapshot. The streaming message is 

https://github.com/etcd-io/etcd/blob/dafc1ade48642a86f3e94cb8204c8a9793a23a95/api/etcdserverpb/rpc.pb.go#L1799-L1814

```go
type SnapshotResponse struct {
	// header has the current key-value store information. The first header in the snapshot
	// stream indicates the point in time of the snapshot.
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// remaining_bytes is the number of blob bytes to be sent after this message
	RemainingBytes uint64 `protobuf:"varint,2,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"`
	// blob contains the next chunk of the snapshot in the snapshot stream.
	Blob []byte `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	// local version of server that created the snapshot.
	// In cluster with binaries with different version, each cluster can return different result.
	// Informs which etcd server version should be used when restoring the snapshot.
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

In order to reduce the number of memory allocation, I am trying to use the pre-allocation for the `Blob` and memory clear after each use.

But it seems that the `SendMsg` will cache the payload if the `EnableTracing` is true. It might cause to output incorrect message if the `Blob` content has been clear. And it is the same to the `StatHandler` if the handler is being lazy.

So, it is good practise for reuse the pre-allocation buffer in this case? For the commnutication, it is safe because marshal always copy the payload. But the trace/things are touching the message after marshal. IMO, the [trace](https://github.com/grpc/grpc-go/blob/eeb9afa1f6b6388152955eeca8926e36ca94c768/stream.go#L1561) should store the truncated bytes instead of the whole message. And if the `StatHandle` modifies the payload later, it might mess up the following sending data. 

Want to get some feedback from team about this case. Looking forward to hearing from you! Thanks

REF: https://github.com/etcd-io/etcd/pull/14918#issuecomment-1345674917

**Comment by dfawley** [comment] 2022-12-13 17:45
> But it seems that the SendMsg will cache the payload if the EnableTracing is true. It might cause to output incorrect message if the Blob content has been clear. And it is the same to the StatHandler if the handler is being lazy.

I think the problem is "after each use" is not defined.  The message passed to `SendMsg` should not be modified after calling `SendMsg`.  I'm not sure there's much we could do about this that doesn't require a new API.  We could try to reference count the message in gRPC and call an optional method on the message when it is no longer needed.  When that method is called, you could add it back to a `sync.Pool` or equivalent.  I'm not sure how much work that would be, but if you're interested in looking into it, I'm open to the idea.  Or if you have alternatives, feel free to propose them.

> if the StatHandle modifies the payload later, it might mess up the following sending data.

This is _definitely_ not supported.  Stats handlers should be gathering stats, not altering any data passed to them.

**Comment by fuweid** [comment] 2022-12-14 16:14
@dfawley Thanks for the quick reply!

I would like to make the comment more clear in the thread(sorry for the unclear first comment). I am trying to use pre-allocated buffer (just for part of message) to send message in one stream call (snapshot api), which can be described by the following code. The size of snapshot can be 120MiB ~ 1GiB. The pre-allocated can reduce memory allocation. And I checked the code about `SendMsg` and found that beside of `StatHandler`/`traceLog`, gRPC framework doesn't use the message after marshal. 

<details>
<summary>Code</summary>

```go
func (ms *maintenanceServer) Snapshot(sr *pb.SnapshotRequest, srv pb.Maintenance_SnapshotServer) error {
	// ...
	
	buf := make([]byte, snapshotSendBufferSize) // 32 KiB

	for total-sent > 0 {
		n, _ := io.ReadFull(pr, buf)
		
		sent += int64(n)

		resp := &pb.SnapshotResponse{
			RemainingBytes: uint64(total - sent),
			Blob:           buf[:n],
			Version:      storageVersion,
		}

		if err = srv.Send(resp); err != nil {
			return togRPCError(err)
		}

		// reset buf
		for idx := range buf {
			buf[idx] = 0
		}
	}
      
        // ...
}
```

</details>

> Stats handlers should be gathering stats, not altering any data passed to them.

Totally agree! And that's why I think the reuse-buffer-method is possible. 😂 

> The message passed to `SendMsg` should not be modified after calling `SendMsg`.

So, is there any reason about `should not be modified after calling SendMsg`? https://pkg.go.dev/google.golang.org/grpc#ServerStream.SendMsg the doc doesn't mention about this. 

>  When that method is called, you could add it back to a sync.Pool or equivalent. I'm not sure how much work that would be, but if you're interested in looking into it, I'm open to the idea.

I am interested in this, but I didn't follow your idea. 😂 

My original through is that if the message can be safely reused after `SendMsg` call, the developer can cache the message by their own. ~

**Comment by dfawley** [comment] 2022-12-14 17:17
> > Stats handlers should be gathering stats, not altering any data passed to them.
> 
> Totally agree! And that's why I think the reuse-buffer-method is possible.

I don't think this matters, actually.  If you modify the message passed to `SendMsg` before the stats handler is called, then you'll be affecting what the handler sees for that message.  And this can happen if you have retry enabled, for example.

> > The message passed to `SendMsg` should not be modified after calling `SendMsg`.
> 
> So, is there any reason about `should not be modified after calling SendMsg`? [pkg.go.dev/google.golang.org/grpc#ServerStream.SendMsg](https://pkg.go.dev/google.golang.org/grpc#ServerStream.SendMsg) the doc doesn't mention about this.

The evidence that you pointed to is the reason.  If the stats handler or tracing library accesses the message in the future, then it would be getting the wrong data (in addition to being a memory race if locks aren't in place).  You're right that this isn't mentioned, and it should be.

> > When that method is called, you could add it back to a sync.Pool or equivalent. I'm not sure how much work that would be, but if you're interested in looking into it, I'm open to the idea.
> 
> I am interested in this, but I didn't follow your idea.

The idea was to notify the application when the message was done being used, e.g. when we were sure the stats handler couldn't be called with that message and when the tracing library was done with it, too (which I believe we can figure out via [`SetRecycler`](https://pkg.go.dev/golang.org/x/net/trace#Trace)?).

It would be nice if we could guarantee that a message was done being used before returning from SendMsg, but it would require breaking our stats API and would make the tracing integration much more expensive.

**Comment by ptabor** [comment] 2022-12-15 15:01
Thank you Doug for answers. The API (or the fact that logging/monitoring handlers are using the data assynchronously) is inconvient and error prone.
I think that we should:
- [ ] document explicitly that stream.Send and SendMsg cannot modify (ever) the value passed. 
- [ ] consider a `SyncSend` variant of the methods that closes when the data are fully consumed

Alternative would be to change logging and monitoring to perform own copy, but:
 - ecosystem wide it would rather not be performance-gain
 - we don't know how many customer's owned interceptors carry simillar assumption of immutability, that we would break.

**Comment by dfawley** [comment] 2022-12-15 16:48
>  document explicitly that stream.Send and SendMsg cannot modify (ever) the value passed.

I agree this would be a good idea.

>  consider a SyncSend variant of the methods that closes when the data are fully consumed

This just isn't possible without a breaking behavior or API change.  Our current stats API expects a pointer to the message.  It also expects to be called on all retry attempts.  Retry attempts can (and in some cases may _only_ be able to) occur after subsequent stream operations.  I am fairly sure we have important use cases where the stats handler requires the message itself.

> we don't know how many customer's owned interceptors carry simillar assumption of immutability, that we would break.

Good point.  In this case, we should document the interceptors as well to indicate they should not assume the message is immutable (except during the call's lifespan of course).

**Comment by easwars** [comment] 2022-12-20 20:16
@fuweid @ptabor 

How would y'all want to proceed with this?

We would be happy to receive PRs for the two items mentioned in the previous conversations:
- documentation changes
- optional method on the message type to enable reference counting (and thereby letting the user know that gRPC is *done* using the provided message).

Thanks

**Comment by dfawley** [comment] 2022-12-20 21:17
> optional method on the message type to enable reference counting (and thereby letting the user know that gRPC is done using the provided message).

We should discuss this a bit more before openly inviting a PR that implements it -- or, at least the PR author should be aware ahead of time that this idea may turn out to be infeasible for a variety of reasons.  This was just an off-the-cuff idea I had for a way to provide the desired functionality here.

**Comment by fuweid** [comment] 2022-12-21 08:49
@easwars and @dfawley 

Sorry for the late reply. I would like to file pr to doc "should not change msg after SendMsg" at first.
And I am still thinking about how to handle the reference counting and might ping you all later before implementation~ :)

**Comment by easwars** [comment] 2022-12-21 16:28
SGTM.

**Comment by easwars** [comment] 2022-12-29 19:20
Given that the documentation update PR has been merged, lets close this issue and open a new one when we want to discuss options for handling reuse of the message. Thanks.

**Closed by easwars** 2022-12-29 19:20 UTC
Labels: Type: Question
