### ISSUE TITLE
Operating on gRPC `metadata.MD` is really hard

### ISSUE THREAD

**Issue by mwitkow-io** [grpc/grpc-go#395] opened 2015-10-09 12:57 UTC
the `metadata.MD` object is the only way to access headers for the RPC, for example the `authenticate: Bearer` token on teh server side.

However, it is incredibly hard to work with. It's hard to:
 * extract a single value under a given header (with binary decode)
 * dd a new value if you want to add it to Metadata you received from a call into another call `encodeKeyValue` is private
 * for some odd reason it supports multiple values per key (is this even allowed by HTTP2?)
 * if you construct new `metadata.MD` using`metadata.New` and then attach it using `metadata.NewContext`, it seems like it will "hide" a previously existing `metadata` value instead of adding to it

Are you guys planning on making it more user friendly? Would you accept PRs to make it so?

**Comment by iamqizhao** [comment] 2015-10-09 18:07
By design, we would like to offer constrained operations on metadata to
prevent misuse.

On Fri, Oct 9, 2015 at 5:57 AM, Michal Witkowski <notifications@github.com>
wrote:

> the metadata.MD object is the only way to access headers for the RPC, for
> example the authenticate: Bearer token on teh server side.
>
> However, it is incredibly hard to work with. It's hard to:
>
>    - extract a single value under a given header (with binary decode)
>
> It is not hard to have your own convenient function to do this. It is also
welcome to contribute to the metadata package.

>
>    - dd a new value if you want to add it to Metadata you received from a
>    call into another call encodeKeyValue is private
>
> I agree we probably should add "Add" public API which is missing. Again,
contribution is welcome.

>
>    - for some odd reason it supports multiple values per key (is this
>    even allowed by HTTP2?)
>
> Yep, comparable to http is the only reason we introduce this.

>
>    - if you construct new metadata.MD usingmetadata.New and then attach
>    it using metadata.NewContext, it seems like it will "hide" a
>    previously existing metadata value instead of adding to it
>
> Which is better semantics is debatable. I think it is fine as long as we
make it clear in the comment.

>
>
> Are you guys planning on making it more user friendly? Would you accept
> PRs to make it so?
>
Any proper contribution is welcome.

**Comment by iamqizhao** [comment] 2015-10-09 18:10
I treated this as a general query instead of some specific issues. I close this one. Feel free to contribute and open issues for particular issues.

**Closed by iamqizhao** 2015-10-09 18:10 UTC
