### ISSUE TITLE
Failed to connect after switching network namespace

### ISSUE THREAD

**Issue by Bugsy71** [grpc/grpc-go#2706] opened 2019-03-21 17:28 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
v1.9.2

### What version of Go are you using (`go version`)?
go1.10.4

### What operating system (Linux, Windows, …) and version?
Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
If possible, provide a recipe for reproducing the error.
I modified the GRPC example 'Hello World' to include a namespace switch in both the server and client.
[helloworld.tar.gz](https://github.com/grpc/grpc-go/files/2993241/helloworld.tar.gz)

 A network namespace was created in a docker container, where both binaries were executed:
> NAMESPACE=fronthaul ../../bin/greeter_server
> NAMESPACE=fronthaul ../../bin/greeter_client

Are there any limitations in GRPC related to network namespace switching? It seems to be related to the client, i.e. grpc.Dial(), as the connection was properly established if I instead executed:
> ip netns exec fronthaul ../../bin/greeter_client 

I've read lot's of articles related to problems with namespace switching due to the Golang runtime environment. I therefore suspect that there might be some goroutine embedded in the grpc.Dial() call, which could be the reason for ending up in the wrong namespace before trying to connect the socket to the server. Is this a known limitation of the GRPC implementation? Any solution to it? I looked for some dial option (like block) to try and solve this, but without any success.
  
### What did you expect to see?
I expected to see something similar to '2019/03/21 16:47:37 Greeting: Hello world' when the client was executed.

### What did you see instead?
could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure

**Comment by dfawley** [comment] 2019-03-22 21:18
@Bugsy71 

Can you try with recent versions of gRPC (1.19) and Go (1.12)?  Also, please run with this set in your environment to collect debugging info: `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info` (client-side only, since you say the server works when you run the client differently).

I'm not aware of this, but it's likely any problems are caused by go's net.Dial since we do create our connections via that.  It may be possible to override the dialer using `grpc.WithDialer` to work around this.

**Comment by Bugsy71** [comment] 2019-03-23 22:41
Sure. This is the result:
client 68ac3588d6:/home/mct/src/ericsson# NAMESPACE=fronthaul ../../bin/greeter_client
* Client thread id before runtime.LockOSThread(): 120
* Client thread id after runtime.LockOSThread(): 120
* Dial in unblocked mode
* Talk to server at localhost:50051
* Switch namespace to fronthaul
* Client thread id before grpc.Dial(): 120
INFO: 2019/03/23 22:36:54 parsed scheme: ""
INFO: 2019/03/23 22:36:54 scheme "" not registered, fallback to default scheme
INFO: 2019/03/23 22:36:54 ccResolverWrapper: sending new addresses to cc: [{localhost:50051 0  <nil>}]
INFO: 2019/03/23 22:36:54 ClientConn switching balancer to "pick_first"
* Client thread id before pb.NewGreeterClient(): 120
* Client thread id after pb.NewGreeterClient(): 120
INFO: 2019/03/23 22:36:54 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, CONNECTING
WARNING: 2019/03/23 22:36:54 grpc: addrConn.createTransport failed to connect to {localhost:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused". Reconnecting...
INFO: 2019/03/23 22:36:54 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, TRANSIENT_FAILURE
could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused"INFO: 2019/03/23 22:36:55 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, CONNECTING
WARNING: 2019/03/23 22:36:55 grpc: addrConn.createTransport failed to connect to {localhost:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused". Reconnecting...
INFO: 2019/03/23 22:36:55 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, TRANSIENT_FAILURE
INFO: 2019/03/23 22:36:57 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, CONNECTING
WARNING: 2019/03/23 22:36:57 grpc: addrConn.createTransport failed to connect to {localhost:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused". Reconnecting...
INFO: 2019/03/23 22:36:57 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, TRANSIENT_FAILURE
INFO: 2019/03/23 22:36:59 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212c0, CONNECTING
WARNING: 2019/03/23 22:36:59 grpc: addrConn.createTransport failed to connect to {localhost:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused". Reconnecting...

**Comment by dfawley** [comment] 2019-03-25 17:52
Thanks.  Would you mind running that again with the working `ip netns exec fronthaul ../../bin/greeter_client` command so we can see what differences there are?

**Comment by Bugsy71** [comment] 2019-03-26 10:42
```
# ip netns exec fronthaul ../../bin/greeter_client
* Client thread id before runtime.LockOSThread(): 104
* Client thread id after runtime.LockOSThread(): 104
* Dial in unblocked mode
* Talk to server at localhost:50051
* Client thread id before grpc.Dial(): 104
INFO: 2019/03/26 10:30:46 parsed scheme: ""
INFO: 2019/03/26 10:30:46 scheme "" not registered, fallback to default scheme
INFO: 2019/03/26 10:30:46 ccResolverWrapper: sending new addresses to cc: [{localhost:50051 0  <nil>}]
INFO: 2019/03/26 10:30:46 ClientConn switching balancer to "pick_first"
* Client thread id before pb.NewGreeterClient(): 104
* Client thread id after pb.NewGreeterClient(): 104
INFO: 2019/03/26 10:30:46 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, CONNECTING
INFO: 2019/03/26 10:30:46 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, READY
* Client thread id after c.SayHello(): 104
2019/03/26 10:30:46 Greeting: Hello world
* Client thread id at exit: 104
```

**Comment by dfawley** [comment] 2019-03-26 18:08
@Bugsy71 - Thanks again for the additional debugging data.

> I get the impression that the output 'pickfirstBalancer: HandleSubConnStateChange' is created by another goroutine than the original where I called grpc.Dial(), so it was scheduled to execute on another OS thread where the namespace was not switched in the previous case. In this case it works as the entire process (all OS threads) executed in the same namespace.

It is possibly called from another OS thread (definitely another goroutine, but threads are less fixed in go's runtime), but that thread would be spawned from the primary process, so it should pick up all the same environment settings.  You could test this theory by setting GOMAXPROCS=1 so that Go only uses one goroutine processor.

By default, grpc just passes the target name straight to golang's `net.Dial`, and if it's not working, then this typically means the problem is not related to grpc.  You should be able to replace `grpc.Dial()` with `net.Dial()` directly and see this same error.  In that case, it's either something wrong with the `netns` library, your usage of it, your configuration, or something at a Go or OS-level.  Please give that a try and let us know what you find.

**Comment by Bugsy71** [comment] 2019-03-27 13:53
Hi,

There seems to be some kind of misunderstanding. After the namespace is switched in the client, the go routine must not be rescheduled to another OS thread to continue execute in the same namespace. That's why the go routine is locked to the OS thread and that's why new go routines spawned will not be able to execute in the same OS thread. Setting GOMAXPROCS will not affect this. The client will still use at least 2 OS threads.

A spawned OS thread will not inherit the namespace set in the client OS thread. There were changes related to this in Go1.10: https://golang.org/doc/go1.10#runtime
This has to be taken into account to be able to support (for instance) namespace switching.

I made a few changes to give some information about the current network namespace of the client. I also made a call to a dummy go routine to illustrate that it will execute in a separate OS thread and therefore in the wrong namespace. This is probably what happens when executing grpc.Dial() and the reason why the socket is created in the wrong namespace.
```
# GOMAXPROCS=1 NAMESPACE=fronthaul ../../bin/greeter_client 
* Client thread id before runtime.LockOSThread(): 158
* Client thread id after runtime.LockOSThread(): 158
* Dial in unblocked mode
* Talk to server at localhost:50051
* Client network namespace is NS(3:4026532839)
* Switch namespace to fronthaul
* Client thread id before grpc.Dial(): 158
* Client network namespace is NS(3:4026533214)
* Client thread id before pb.NewGreeterClient(): 158
* Client network namespace is NS(3:4026533214)
* Client thread id after pb.NewGreeterClient(): 158
* Client network namespace is NS(3:4026533214)
* Client thread id in dummyGR(): 160
* Client network namespace is NS(3:4026532839)
could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused"
```
Not sure what you mean when you ask me to 'replace grpc.Dial() with net.Dial()'. That will affect the type of 'conn' and introduce build errors.

[grpctest.tar.gz](https://github.com/grpc/grpc-go/files/3013394/grpctest.tar.gz)

**Comment by dfawley** [comment] 2019-03-27 16:03
@Bugsy71 I think I have a solution for you - you can pass a custom dialer to `grpc.Dial` to switch the namespace before connecting:

```go
  grpc.Dial(...,
    grpc.WithDialer(func(string, time.Duration) (net.Conn, error) {
       // Lock OS thread, set namespace, call net.Dial, unlock OS thread, and return result.
    }))`
```

That should solve the problem of being able to connect - let me know if the approach works for you.

> Not sure what you mean when you ask me to 'replace grpc.Dial() with net.Dial()'. That will affect the type of 'conn' and introduce build errors.

Sorry, I meant to try this just for debugging purposes to see if an error would come out, not as a solution.

**Comment by Bugsy71** [comment] 2019-03-27 18:00
Thanks! This is interesting.

It seems to work for the example code, though I seem to generate multiple connection attempts (message about switching namespace appeared a couple of times). I'll have a look at this tomorrow to see if I understand why this happened.

A question related to this custom dialer. I have to use TLS in my real application (i.e. not the grpc example). Will  that dial option be compatible to the custom dialer I just added?

```
# NAMESPACE=fronthaul DIALBLOCK="t" ../../bin/greeter_client 
* Talk to server at localhost:50051
* Client network namespace is NS(3:4026533492)
* Dial in blocked mode
* Client thread id before grpc.Dial(): 112
* Client network namespace is NS(3:4026533492)
* Client thread id in dummyGR(): 114
* Switch namespace to fronthaul
* Client network namespace is NS(3:4026533492)
* Switch namespace to fronthaul
* Switch namespace to fronthaul
* Switch namespace to fronthaul
* Switch namespace to fronthaul
* Switch namespace to fronthaul
* Switch namespace to fronthaul
* Client thread id before pb.NewGreeterClient(): 121
* Client network namespace is NS(3:4026533705)
* Client thread id after pb.NewGreeterClient(): 121
* Client network namespace is NS(3:4026533705)
* Client thread id after c.SayHello(): 121
* Client network namespace is NS(3:4026533705)
2019/03/27 17:44:34 Greeting: Hello world
* Client thread id at exit: 122
* Client network namespace is NS(3:4026533492)
```

**Comment by dfawley** [comment] 2019-03-27 19:48
> It seems to work for the example code, though I seem to generate multiple connection attempts (message about switching namespace appeared a couple of times). I'll have a look at this tomorrow to see if I understand why this happened.

If you turn on the debugging output again on the client as well as the server, you may find the cause.

> A question related to this custom dialer. I have to use TLS in my real application (i.e. not the grpc example). Will that dial option be compatible to the custom dialer I just added?

Yes, TLS will still be used with a custom dialer if it's set in the dial options.  The only thing that you would lose is our support for a proxy set in your environment.  If you need to support a local proxy in addition to the namespace switching, you would have to reimplement that part yourself.

**Comment by Bugsy71** [comment] 2019-03-28 13:34
Great that I'll be able to use TLS. No I don't have any need for any advanced GRPC features like proxy.

Regarding the custom dialer approach:
It seems like I have to use blocking dial(?). That's not  a problem, but I would like to get that confirmed.
Each connection attempt seems to operate in the correct namespace:
```
 # ls -i /var/run/netns/fronthaul 
4026533705 /var/run/netns/fronthaul
```
```
# NAMESPACE=fronthaul DIALBLOCK="t" ../../bin/greeter_client 
* Talk to server at localhost:50051
* Client network namespace is NS(3:4026533492)
* Dial in blocked mode
* Client thread id before grpc.Dial(): 209
* Client network namespace is NS(3:4026533492)
* Client thread id in dummyGR(): 214
* Client network namespace is NS(3:4026533492)
INFO: 2019/03/28 12:53:54 parsed scheme: ""
INFO: 2019/03/28 12:53:54 scheme "" not registered, fallback to default scheme
INFO: 2019/03/28 12:53:54 ccResolverWrapper: sending new addresses to cc: [{localhost:50051 0  <nil>}]
INFO: 2019/03/28 12:53:54 ClientConn switching balancer to "pick_first"
INFO: 2019/03/28 12:53:54 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, CONNECTING
* Switch namespace to fronthaul
* Client thread id before net.Dial(): 209
* Client network namespace is NS(3:4026533705)
* Client thread id at end of custom dialer: 209
* Client network namespace is NS(3:4026533705)
WARNING: 2019/03/28 12:53:54 grpc: addrConn.createTransport failed to connect to {localhost:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused". Reconnecting...
INFO: 2019/03/28 12:53:54 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, TRANSIENT_FAILURE
* Switch namespace to fronthaul
* Client thread id before net.Dial(): 214
* Client network namespace is NS(3:4026533705)
INFO: 2019/03/28 12:53:55 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, CONNECTING
* Client thread id at end of custom dialer: 214
* Client network namespace is NS(3:4026533705)
WARNING: 2019/03/28 12:53:55 grpc: addrConn.createTransport failed to connect to {localhost:50051 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused". Reconnecting...
INFO: 2019/03/28 12:53:55 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, TRANSIENT_FAILURE
* Switch namespace to fronthaul
INFO: 2019/03/28 12:53:57 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, CONNECTING
* Client thread id before net.Dial(): 216
* Client network namespace is NS(3:4026533705)
* Client thread id at end of custom dialer: 216
* Client network namespace is NS(3:4026533705)
INFO: 2019/03/28 12:53:57 pickfirstBalancer: HandleSubConnStateChange: 0xc0000212a0, READY
* Client thread id before pb.NewGreeterClient(): 217
* Client network namespace is NS(3:4026533492)
* Client thread id after pb.NewGreeterClient(): 217
* Client network namespace is NS(3:4026533492)
* Client thread id after c.SayHello(): 215
* Client network namespace is NS(3:4026533492)
2019/03/28 12:53:57 Greeting: Hello world
* Client thread id at exit: 214
* Client network namespace is NS(3:4026533705)
 ```
I assume that the socket is created as part of the net.Dial() call(?), so once the custom dialer has completed its work, the socket exists and can therefore be used from any namespace (RPC calls will be scheduled to different OS threads as go routine is only locked to OS thread while in the custom dialer).

**Comment by dfawley** [comment] 2019-03-29 22:51
> It seems like I have to use blocking dial(?). That's not a problem, but I would like to get that confirmed.

I don't know why you believe this would be a requirement.  Non-blocking *should* work, too.

> I assume that the socket is created as part of the net.Dial() call(?), so once the custom dialer has completed its work, the socket exists and can therefore be used from any namespace

That was what I was thinking as well.

**Comment by Bugsy71** [comment] 2019-04-01 14:46
Well, I guess I just wanted the actual behaviour to be the expected. I definitely don't get any connection when I use the non-blocking mode. When in blocking the mode, the connection is established after a few attempts (as shown above). I guess I can try strace to figure out why the first attempts fail.

I probably need better knowledge to understand how this blocking option affects GRPC. Any documentation about grpc.Dial() and the related dial options available, or do you recommend a deep dive into the source code? :-)

**Comment by dfawley** [comment] 2019-04-01 16:14
`WithBlock` doesn't change much in what we do.  All it does is make `Dial`, after doing everything it normally does, wait until the connectivity status says it is connected.

**Comment by dfawley** [comment] 2019-04-01 16:28
You may want to try setting `GOMAXPROCS=1` in your environment (or in `main()`).  If that fixes your problems, then I think your assumption (and mine) may be wrong, and that reads/writes on the `Conn` may need to be done on the same thread:

> I assume that the socket is created as part of the net.Dial() call(?), so once the custom dialer has completed its work, the socket exists and can therefore be used from any namespace

If that is the case, I'm not sure how this can work in gRPC, since we probably don't want to pin the reader/writer goroutines to the same thread that dialed just for this one use case.

**Comment by Bugsy71** [comment] 2019-04-02 11:45
> You may want to try setting GOMAXPROCS=1 in your environment (or in main()). If that fixes your problems, then I think your assumption (and mine) may be wrong, and that reads/writes on the Conn may need to be done on the same thread:

The behaviour was more or less the same when I tried this (non-blocking mode does not work, blocking works after a few 'glitches'). Fewer OS threads were used, but it is not possible to force the client to use only one OS thread. There would be a risk of deadlock situations in case it was possible, but that is not the purpose of the variable.

It was a quick one to try, though I don't understand what changed behaviour you anticipated.

**Comment by dfawley** [comment] 2019-04-02 17:49
I was/am expecting that with only one goroutine processor, only 1 OS thread will be able to run go code:

https://golang.org/pkg/runtime/#hdr-Environment_Variables:
> The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously.

It's possible "only one simultaneously" isn't the same as "only one ever exists".

I'm not really sure where to go from here.  Any remaining issues are most likely in the `netns` library or its limitations or your usage of it -- or maybe some configuration issue.  I believe the errors you're seeing in the debugging output are coming directly from your custom dialer - you could try logging them when `net.Dial` returns an error.  I don't expect you would see any extra info to help you debug, but it would pinpoint the problem.  (If you were to put those `net.Dial` calls directly in your `main`, I expect you would see similar errors.)

`WithBlock` is only helping vs. non-blocking mode if you are performing non-wait-for-ready RPCs (which is the default), because `WithBlock` waits for a `Ready` connection before returning, and the connection is failing a few times initially.  This transient failure makes non-wait-for-ready RPCs fail instead of queuing.

**Comment by Bugsy71** [comment] 2019-04-05 10:09
Yes there's definitely a difference. If GOMAXPROCS=1 would have turned this into a single OS thread app, there could have been a deadlock situation. The first OS thread is locked to the goroutine executing the custom dialer, so that can't be used  by any other goroutine required to execute. Don't know if the hello world example would have been in a deadlock situation, but a generic app would definitely be at risk in case GOMAXPROCS=1 would have had the impact you suggested.

I did another experiment, where I used the same example but replaced grpc with a plain and simple net.Conn connection. I experienced no problems with these greeter_client/server. Network namespace was switched before the Dial(), but still the Read() and Write() executed perfectly in other OS threads using the 'wrong namespace'. As long as the 'socket' (net.Conn) is created in the correct namespace, it can be used from everywhere. Unfortunately, such a solution is not good enough for my real application where I need support for TLS.

**Comment by Bugsy71** [comment] 2019-04-05 13:28
Major breakthrough!
 It seems like the dial problems are related to resolver issues. When I change 'localhost' to '127.0.0.1', the glitches seem to be gone. As there are no Dial problems anymore, even unblocked mode works the way it should (though I still don't need it :-) ). Time to adapt my real application to this custom dialer approach...
```
# DIALBLOCK=1 NAMESPACE=fronthaul ../../bin/greeter_client
* Talk to server at localhost:50051
* Client at start: thread=301, netns=NS(3:4026533052)
* Dial in blocked mode
* Client before grpc.Dial(): thread=301, netns=NS(3:4026533052)
* Client at start of custom dialer (addr=localhost:50051, timout=19999973922): thread=301, netns=NS(3:4026533052)
* Switch namespace to fronthaul
* Client before net.Dial(): thread=301, netns=NS(3:4026533571)
* Client failed to execute net.Dial() dial tcp [::1]:50051: connect: connection refused: thread=301, netns=NS(3:4026533571)
* Client at start of custom dialer (addr=localhost:50051, timout=19999983045): thread=304, netns=NS(3:4026533052)
* Switch namespace to fronthaul
* Client before net.Dial(): thread=304, netns=NS(3:4026533571)
* Client failed to execute net.Dial() dial tcp [::1]:50051: connect: connection refused: thread=304, netns=NS(3:4026533571)
* Client at start of custom dialer (addr=localhost:50051, timout=19999982726): thread=304, netns=NS(3:4026533571)
* Switch namespace to fronthaul
* Client before net.Dial(): thread=304, netns=NS(3:4026533571)
* Client after net.Dial(): thread=304, netns=NS(3:4026533571)
* Client at end of custom dialer: thread=304, netns=NS(3:4026533571)
* Client before pg.NewGreeterClient(): thread=301, netns=NS(3:4026533571)
* Client after pb.NewGreeterClient(): thread=301, netns=NS(3:4026533571)
* Client before c.SayHello(): thread=301, netns=NS(3:4026533571)
* Client after c.SayHello(): thread=310, netns=NS(3:4026533571)
2019/04/05 13:06:27 Greeting: Hello world
* Client at exit: thread=308, netns=NS(3:4026533052)
```
vs
```
# ADDRESS=127.0.0.1:50051 DIALBLOCK=1 NAMESPACE=fronthaul ../../bin/greeter_client
* Talk to server at 127.0.0.1:50051
* Client at start: thread=311, netns=NS(3:4026533052)
* Dial in blocked mode
* Client before grpc.Dial(): thread=311, netns=NS(3:4026533052)
* Client at start of custom dialer (addr=127.0.0.1:50051, timout=19999977051): thread=311, netns=NS(3:4026533052)
* Switch namespace to fronthaul
* Client before net.Dial(): thread=311, netns=NS(3:4026533571)
* Client after net.Dial(): thread=311, netns=NS(3:4026533571)
* Client at end of custom dialer: thread=311, netns=NS(3:4026533571)
* Client before pg.NewGreeterClient(): thread=314, netns=NS(3:4026533052)
* Client after pb.NewGreeterClient(): thread=314, netns=NS(3:4026533052)
* Client before c.SayHello(): thread=314, netns=NS(3:4026533052)
* Client after c.SayHello(): thread=311, netns=NS(3:4026533571)
2019/04/05 13:16:23 Greeting: Hello world
* Client at exit: thread=313, netns=NS(3:4026533052)
```
vs

```
# ADDRESS=127.0.0.1:50051 NAMESPACE=fronthaul ../../bin/greeter_client
* Talk to server at 127.0.0.1:50051
* Client at start: thread=318, netns=NS(3:4026533052)
* Dial in unblocked mode
* Client before grpc.Dial(): thread=318, netns=NS(3:4026533052)
* Client before pg.NewGreeterClient(): thread=318, netns=NS(3:4026533052)
* Client after pb.NewGreeterClient(): thread=318, netns=NS(3:4026533052)
* Client before c.SayHello(): thread=318, netns=NS(3:4026533052)
* Client at start of custom dialer (addr=127.0.0.1:50051, timout=19999971114): thread=320, netns=NS(3:4026533052)
* Switch namespace to fronthaul
* Client before net.Dial(): thread=320, netns=NS(3:4026533571)
* Client after net.Dial(): thread=320, netns=NS(3:4026533571)
* Client at end of custom dialer: thread=320, netns=NS(3:4026533571)
* Client after c.SayHello(): thread=318, netns=NS(3:4026533052)
2019/04/05 13:18:33 Greeting: Hello world
* Client at exit: thread=318, netns=NS(3:4026533052)
```

**Comment by Bugsy71** [comment] 2019-04-10 19:40
I just want to confirm that this solution works for my real application as well. Problem solved. Thanks for providing information about the custom dialer.

**Comment by dfawley** [comment] 2019-04-10 21:01
Great, glad to hear everything worked out!

**Closed by dfawley** 2019-04-10 21:01 UTC
Labels: Status: Requires Reporter Clarification
