### ISSUE TITLE
Server.handleStream silently drops errors

### ISSUE THREAD

**Issue by alecthomas** [grpc/grpc-go#3740] opened 2020-07-15 00:11 UTC
[Server.handleStream](https://github.com/grpc/grpc-go/blob/master/server.go#L1503-L1513) silently drops all errors from processUnaryRPC and processStreamingRPC. It should at least log the errors.

We noticed this because a client in another language enabled gzip encoding and there were no errors in the Go gRPC server at all.

**Comment by dfawley** [comment] 2020-07-15 17:30
Most errors that would be returned by these functions are returned to the client directly first.  Did the client not see an error message about the unsupported encoding in this case?

In this particular case, this "error" doesn't really seem like something we need to log on the server side.  If we did, it would be informational, at a higher verbosity, or something we'd need to throttle so it is only displayed once.  Otherwise, a client could flood the server's logs by requesting a non-existent codec.

**Comment by alecthomas** [comment] 2020-07-16 05:59
No, there were no errors on the client side. The client just received a 200 with an empty response body.

Irrespective of the merits of logging in this particular case, swallowing errors is not good practice and _any_ error from these methods is dropped, not just compression negotiation failures.

**Comment by dfawley** [comment] 2020-07-16 15:47
> No, there were no errors on the client side. The client just received a 200 with an empty response body.

We would expect HTTP status 200 for all gRPC responses, even errors.  The client should be receiving an UNIMPLEMENTED RPC status code as the grpc-status.  If you aren't seeing one, could you provide a reproduction test case for us so we can look into the issue?

> Irrespective of the merits of logging in this particular case, swallowing errors is not good practice and any error from these methods is dropped, not just compression negotiation failures.

I agree swallowing errors is bad practice.  To address this, we will most likely stop returning an error from these functions, since we are the ones that produce them (and consume them -- [in this case, by writing a status back to the client](https://github.com/grpc/grpc-go/blob/master/server.go#L1119-L1120)).

**Comment by zhxnlai** [comment] 2020-07-16 18:01
I was able to reproduce this using a [Java client](https://github.com/square/wire/blob/master/wire-library/docs/wire_grpc.md) (using gzip) and a go gRPC server (without `google.golang.org/grpc/encoding/gzip` installed).

The server sent back the following response:

<img width="1017" alt="Screen Shot 2020-07-16 at 9 52 02 AM" src="https://user-images.githubusercontent.com/4694896/87699729-25912d00-c74a-11ea-9bfa-141bdf8512b9.png">
<img width="1158" alt="Screen Shot 2020-07-16 at 10 31 44 AM" src="https://user-images.githubusercontent.com/4694896/87704218-eb775980-c750-11ea-9474-f8f178abc60f.png">

When client received the response, it tried to read a message from the [data frame](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md#data-frames) and then [read the grpc error status](https://github.com/square/wire/blob/4bc00312f4dd26d5ef63605a656512177f0753b9/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcCall.kt#L65). Because there is no message to read in this response, the client throws a ["No message exception"](https://github.com/square/wire/blob/5b77895f328d2c17716e05826bcfe9e9818c8ff2/wire-library/wire-grpc-client/src/commonMain/kotlin/com/squareup/wire/internal/GrpcMessageSource.kt#L65) right away without looking at the error status. 

This is why on the client side, we didn't see error messages from the server and thought the server dropped the request silently.

To improve the client behavior, should we reverse the order of [L65](https://github.com/square/wire/blob/5b77895f328d2c17716e05826bcfe9e9818c8ff2/wire-library/wire-grpc-client/src/commonMain/kotlin/com/squareup/wire/internal/GrpcMessageSource.kt#L65) and [L66](https://github.com/square/wire/blob/5b77895f328d2c17716e05826bcfe9e9818c8ff2/wire-library/wire-grpc-client/src/commonMain/kotlin/com/squareup/wire/internal/GrpcMessageSource.kt#L66)?

**Comment by dfawley** [comment] 2020-07-16 18:32
@ejona86 to advise about the Java exception.

**Comment by ejona86** [comment] 2020-07-16 18:38
That is not the grpc-java client. It is using Wire. We are not familiar with Wire; consider filing an issue on their repository. If Wire doesn't handle the grpc-status properly, it isn't speaking gRPC. That's very basic gRPC behavior, so I'd just expect it is a configuration problem of some sort.

**Comment by menghanl** [comment] 2020-07-23 20:15
This seems to be a wire bug, and is fixed now.
Closing. Please reply if there's anything remaining to be done.

**Closed by menghanl** 2020-07-23 20:15 UTC
Labels: Status: Requires Reporter Clarification, Type: Bug
