### ISSUE TITLE
Stream doesn't know that transport is broken

### ISSUE THREAD

**Issue by ghost** [grpc/grpc-go#154] opened 2015-04-07 09:36 UTC
How to reproduce:
1. Do normal server streaming rpc
2. Streaming runs smoothly
3. Turn off network
4. ClientStream.RecvMsg() waits indefinitely, there's no way to cancel
    ServerStream.SendMsg() successfully sending (nil error) until, I assume, transport.defaultWindowSize, there's no way to cancel()
This happens no matter how long I turn off the network.

Expectation:
1. Provide a way to cancel method instead of waiting indefinitely.
2. Stream should be aware of broken transport in the middle of transmission

I provide [a gist](https://gist.github.com/prazzt/3fb36ed470d7dd16dd34) to help reproduce the problem

**Comment by yinhm** [comment] 2015-04-09 08:11
I encountered another stream dead lock, 

 * server stream handler return error
 * client waits indefinitely(I could use a timeout contenxt, but it wasn't what I want)

I want to produce it by tests then report it, just not have time yet.

**Comment by iamqizhao** [comment] 2015-04-15 20:26
I think this is due to the lack of a health checking mechanism to detect the state of transport when no TCP signal (e.g., RST) is generated. The health checking is on our radar but the detailed design has not been fleshed out.  For now, you can set a timeout for the entire stream as a workaround. BTW, you can always cancel the rpc via the context binding with the rpc.

For yinhm's question, I have no clue from your simplistic description. Let me know when you have a reproduction.

**Comment by iamqizhao** [comment] 2015-05-11 20:50
The thread is unresponsive for long time. close it for now. Feel free to reopen if it sustains.

**Closed by iamqizhao** 2015-05-11 20:50 UTC
