### ISSUE TITLE
http2Server.HandleStreams failed to read frame ...  use of closed network connection

### ISSUE THREAD

**Issue by bioothod** [grpc/grpc-go#1053] opened 2017-01-20 15:58 UTC
```
transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:8080->127.0.0.1:56140: use of closed network connection
```

I get this error very frequently during usual operations (request-response, no streaming), server stops responding just after few requests after it has been shown in the logs. Client connects but hangs.
Client is written in python, if that matters, below is the tail of the trace
```
(peer=ipv4:127.0.0.1:8080): 67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding'
D0120 18:53:35.079893197    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 15 '.'
D0120 18:53:35.079900652    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'
D0120 18:53:35.079907722    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 40 02 '@.'
D0120 18:53:35.079914199    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 74 65 'te'
D0120 18:53:35.079920624    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 08 '.'
D0120 18:53:35.079927281    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 74 72 61 69 6c 65 72 73 'trailers'
D0120 18:53:35.079933853    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 40 0c '@.'
D0120 18:53:35.079940642    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 63 6f 6e 74 65 6e 74 2d 74 79 70 65 'content-type'
D0120 18:53:35.079947042    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 10 '.'
D0120 18:53:35.079954235    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 61 70 70 6c 69 63 61 74 69 6f 6e 2f 67 72 70 63 'application/grpc'
D0120 18:53:35.079961223    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 40 0a '@.'
D0120 18:53:35.079967669    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 75 73 65 72 2d 61 67 65 6e 74 'user-agent'
D0120 18:53:35.079974061    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 32 '2'
D0120 18:53:35.079981812    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 50 79 74 68 6f 6e 2d 67 52 50 43 2d 31 2e 30 2e 34 20 67 72 70 63 2d 63 2f 31 2e 30 2e 31 20 28 6d 61 6e 79 6c 69 6e 75 78 3b 20 63 68 74 74 70 32 29 'Python-gRPC-1.0.4 grpc-c/1.0.1 (manylinux; chttp2)'
D0120 18:53:35.079990118    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 00 00 04 08 00 00 00 00 01 00 00 ff ff 00 00 '...............'
D0120 18:53:35.079997916    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 0d 00 01 00 00 00 01 00 00 00 00 08 0a 06 61 '..............a'
D0120 18:53:35.080005051    9288 tcp_posix.c:405]            WRITE 0x55f85b44d9f0 (peer=ipv4:127.0.0.1:8080): 6d 61 7a 6f 6e 'mazon'
D0120 18:53:35.080034782    9288 chttp2_transport.c:675]     W:0x55f85b606d70 WRITING -> INACTIVE because terminate_writing
I0120 18:53:35.279304104    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:35.279351411    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927615, tv_nsec: 479346764, clock_type: 1 }, reserved=(nil))
I0120 18:53:35.479600966    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:35.479637071    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927615, tv_nsec: 679632041, clock_type: 1 }, reserved=(nil))
I0120 18:53:35.679888501    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:35.679923695    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927615, tv_nsec: 879918449, clock_type: 1 }, reserved=(nil))
I0120 18:53:35.880187881    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:35.880224235    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927616, tv_nsec: 80219363, clock_type: 1 }, reserved=(nil))
I0120 18:53:36.080563629    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:36.080604930    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927616, tv_nsec: 280599705, clock_type: 1 }, reserved=(nil))
I0120 18:53:36.280876915    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:36.280925668    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927616, tv_nsec: 480920166, clock_type: 1 }, reserved=(nil))
I0120 18:53:36.481174706    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:36.481211857    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927616, tv_nsec: 681206979, clock_type: 1 }, reserved=(nil))
I0120 18:53:36.681416250    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:36.681450708    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927616, tv_nsec: 881446184, clock_type: 1 }, reserved=(nil))
I0120 18:53:36.881702944    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:36.881744110    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927617, tv_nsec: 81738749, clock_type: 1 }, reserved=(nil))
I0120 18:53:37.082095945    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
I0120 18:53:37.082136020    9288 completion_queue.c:333]     grpc_completion_queue_next(cc=0x55f85b5c7db0, deadline=gpr_timespec { tv_sec: 1484927617, tv_nsec: 282131502, clock_type: 1 }, reserved=(nil))
^CI0120 18:53:37.282403669    9288 completion_queue.c:394]     RETURN_EVENT[0x55f85b5c7db0]: QUEUE_TIMEOUT
```

**Comment by MakMukhi** [comment] 2017-01-20 19:11
Hey,

If I understand this correct, you have a server written in Golang and a
client written in Python?

Some from the top of my head debugging:
It seems like the server expects to read something from the connection but
it's being closed prematurely. When you say "client connects", do you mean
that you dial every time you're sending an rpc request? If so, I'd make
sure that the client closes the previous connections.

Regards,
Mak

**Comment by bioothod** [comment] 2017-01-20 19:21
Yes, you are right, server is written in golang and client is written in python
Here is a 6-line test app I use: https://github.com/grpc/grpc-go/issues/1054

Since client application exits, all its sockets are pretty much closed, and it would be a little bit weird if new client would suddenly get a connection from some other client and server would want to write reply into that old connection.

**Comment by bioothod** [comment] 2017-02-01 21:55
I've posted detailed description of the problem and its root (or something closer to root - grpc-go servers fails to tolerate `bufio.Flush()` error when it writes not whole buffer into the connection`
https://github.com/grpc/grpc-go/issues/1054

**Comment by menghanl** [comment] 2017-02-06 19:29
Duplicate of #1054

**Closed by menghanl** 2017-02-06 19:29 UTC
