### ISSUE TITLE
Document that `ClientStream.SendMsg()` returns `nil` on success for unary/server-streaming RPCs

### ISSUE THREAD

**Issue by ash2k** [grpc/grpc-go#7230] opened 2024-05-13 11:25 UTC
### Use case(s) - what problem will this feature solve?

When a unary RPC is called, this code gets executed:

https://github.com/grpc/grpc-go/blob/59954c80165855ecd478a79e75bcc7d64f629ded/call.go#L65-L74

`SendMsg()` docs say this:

https://github.com/grpc/grpc-go/blob/59954c80165855ecd478a79e75bcc7d64f629ded/stream.go#L112-L115

I have a test for something unrelated where the server immediately returns an error. Very rarely, depending on the timing my test gets `EOF` instead of the error that the server returns. This is because server is occasionally faster than the client. It occurred to me that this is an issue for all unary RPCs - there is no way to get the actual error as the stream is not exposed to the user.

### Proposed Solution

Check for `io.EOF` from `SendMsg()` and call `RecvMsg()` to get the actual error, return it.

### Alternatives Considered

Leave it as is. This might be a requirement to be consistent with other implementations (I have not checked). Perhaps gRPC spec needs to be adjusted/clarified to change the behavior in this case.

### Additional Context

gRPC v1.63.2.
Go 1.22.3

**Comment by ash2k** [comment] 2024-05-17 00:50
To be clear, I don't have bandwidth to work on the fix myself.

**Comment by dfawley** [comment] 2024-05-17 01:37
No problem!  This is rare but probably important enough that we should prioritize this internally.

**Comment by Kailun2047** [comment] 2024-05-17 01:38
@dfawley Hi, is it possible for me pick this one up? Looks like we need to get the following done (please correct me if I'm wrong):

1. create a test that can reliably reproduce the scenario where `SendMsg` returns `io.EOF` (server closes connection before client actually sends?) and the client doesn't get the expected actual error

2. implement the proposed solution and make sure it make the test pass

**Comment by dfawley** [comment] 2024-05-17 01:42
@Kailun2047 Sure, that sounds good to me, as long as you think you can work on it pretty soon.

For the repro, I wonder if we can reproduce it by making a large request, and configure the server with a very small initial window size.  That way the client won't be able to send the full request as long as the server handler treats the method as streaming.  That should make it 100% reproducible, and be fairly simple to do.

**Comment by Kailun2047** [comment] 2024-05-17 01:47
@dfawley Got it. Will try to delve in and make an update here within a day or two.

**Comment by Kailun2047** [comment] 2024-05-20 06:53
@dfawley Hi, I tried creating a [test](https://github.com/Kailun2047/grpc-go/blob/fix/invoke-eof/test/invoke_test.go#L109-L144) per earlier discussion to reproduce but had no luck :sweat_smile:

But upon some initial inspection, looks like the `EOF` reported might not originate from `SendMsg`. Concretely, for invocation of an unary RPC,

* client stream is created with [`unaryStreamDesc`](https://github.com/grpc/grpc-go/blob/master/call.go#L63), which has `ClientStreams` set to `false`

* when sending message with the client stream, the stream [will not return `EOF` for non-client-streaming RPCs](https://github.com/grpc/grpc-go/blob/master/stream.go#L1046-L1054)

Instead, it looks to me that the source of the `EOF` might be a different issue in `RecvMsg`. Concretely,

* [`recvMsg`](https://github.com/grpc/grpc-go/blob/master/stream.go#L1086-L1096) might return `EOF` to indicate end of stream

* the upper level [`RecvMsg`](https://github.com/grpc/grpc-go/blob/master/stream.go#L919) gets the `EOF` returned and calls [`finish`](https://github.com/grpc/grpc-go/blob/master/stream.go#L1135) with it. Looks like we expect `finish` to convert `EOF` to `nil` but the [conversion](https://github.com/grpc/grpc-go/blob/master/stream.go#L1142-L1145) isn't likely to work because the original error is passed in by value instead of by reference.

I'm definitely willing to put more investigation into this, but let me know if you are concerned about the timing and need to prioritize internally :smile:

**Comment by dfawley** [comment] 2024-05-21 15:47
Oh interesting.  I thought it was something simpler, but you're right - some of the streaming code actually checks the type of the RPC and adjusts its behavior accordingly.  If you're able to get to the bottom of this, we would definitely appreciate it.  No worries on the timing at all - I don't think it's as urgent if it's a pretty rare occurrence.

**Comment by Kailun2047** [comment] 2024-05-30 01:59
@ash2k Hi - since we now might have a bigger space to search for the potential source of the `EOF`, is it possible to share more info about the test mentioned in OP? Specifically, are there any `ServerOption`/`DialOption`/`CallOption` being used there? Any other info will also be appreciated. Thanks!

The [existing gRPC tests](https://github.com/grpc/grpc-go/blob/master/test/invoke_test.go#L82-L107) around `Invoke` (in which server also return error immediately) don't seem to help reproduce so I figure there could be something missing.

**Comment by ash2k** [comment] 2024-05-30 02:39
Without going into details, my code emulates a unary RPC over a streaming RPC. That's probably why you cannot reproduce the issue.

> when sending message with the client stream, the stream [will not return EOF for non-client-streaming RPCs](https://github.com/grpc/grpc-go/blob/master/stream.go#L1046-L1054)

This means code in `invoke()` relies on an undocumented behavior that `EOF` is not returned from `SendMsg()` if it's a unary RPC. I see two options:

- This behavior should be documented as part of the `SendMsg()` doc.
- Special behavior that you linked to can be removed and code in `invoke()` should handle the general documented behavior of `SendMsg()`. It's a matter of moving the `if`.

**Comment by Kailun2047** [comment] 2024-06-03 14:46
@dfawley Whoops, turned out initially I had some misunderstanding on the issue :sweat_smile: But I think I get it now (thanks to @ash2k 's response):

1. emulating the unary RPC client's `SendMsg` & `RecvMsg` [sequence](https://github.com/grpc/grpc-go/blob/master/call.go#L70-L73) on a streaming RPC client doesn't quite work ([repro](https://github.com/Kailun2047/grpc-go/blob/fix/invoke-eof/test/end2end_test.go#L6056-L6095)), because an additional check for `EOF` from `SendMsg` is needed
2. the `SendMsg` & `RecvMsg` sequence does work for unary RPC (i.e. `invoke`) though, because of the behavior `SendMsg` has on non-streaming RPC type
3. we might want to adjust documentation/implementation of `SendMsg` per suggested by @ash2k to avoid potential confusion (in our case it makes user suspect that `invoke` doesn't handle return value of `SendMsg` properly)

Sounds like documentation update is an easier option, but let me know if there's more to considerate :smiley:

**Comment by arjan-bal** [comment] 2024-06-05 09:26
I'm leaning towards getting rid of the special handling of non-streaming RPCs in [sendMsg](https://github.com/grpc/grpc-go/blob/master/stream.go#L1046-L1054) and handling the io.EOF in [invoke](https://github.com/grpc/grpc-go/blob/59954c80165855ecd478a79e75bcc7d64f629ded/call.go#L65-L74). This would unify the behaviour for both kinds of RPCs and make the function easier to reason about.

The special handling in sendMsg has been there for for quite some time and the comment was changed 6 years ago in https://github.com/grpc/grpc-go/pull/1854

So I'm concerned about accidentally changing any user facing behaviour. Let me discuss with the team and share an update.

**Comment by arjan-bal** [comment] 2024-06-18 18:18
Assigning to @dfawley to comment on the preferred fix. Since he's presently on vacation, expect a reply by end of the week.

**Comment by dfawley** [comment] 2024-06-27 17:17
Returning `io.EOF` here would break existing code quite badly - our generated code relies upon `SendMsg` not returning an error on success.  So we should update the docs to say something like: for `ClientStreams=false` streams, `nil` is returned unconditionally.

**Closed** 2024-11-11 09:18 UTC
Labels: Type: Documentation, P2
