### ISSUE TITLE
Server Option to Force TLS Peers to Reauthenticate When Presented Cert Expires

### ISSUE THREAD

**Issue by ben-krieger** [grpc/grpc-go#3021] opened 2019-09-13 16:08 UTC
### Use case(s) - what problem will this feature solve?

In a service architecture where each service is issued a short-lived x509 certificate, which is regularly renewed, for TLS mutual auth, it is useful for servers to force their clients to reconnect when their certificate is set to expire.

Examples of RPCs or middleware that might expect the client to be using its latest renewed certificate or care if renewal did not occur and the service has an expired cert:

- Checking the OCSP status of a certificate
- Using `(*x509.Certificate).Verify` to check if the peer certificate is anchored by `*x509.CertPool` A or B
- A PKI service's RenewCertificate RPC might use the peer cert for lookup/validation of request 

A TLS connection by design may continue to work regardless of the times at which the peer certificates expire, so this feature must be enabled at the application level. The best way to handle forcing the client to reconnect is to set a deadline on the conn  equal to the client certificate's `NotAfter` field.

### Alternatives Considered

There are not many hooks into `grpc-go` which allow access to a `net.Conn`. First I tried wrapping the credentials from `credentials.NewTLS` and overriding the `ServerHandshake` func to set a deadline on the conn after doing the TLS handshake.

This does not work, because there's already (rightly) a deadline in place related to the `grpc.ConnectionTimeout` option which gets cleared here: https://github.com/grpc/grpc-go/blob/v1.23.1/server.go#L663

After realizing this, I decided to use a channel to try sending the `net.Conn` to be received in an `InTapHandle` and the deadline to be set there, but this is a poor design, because there's no guarantee that after a connection is made that there will immediately be an RPC called. (At this point there's a question of buffering the channel, etc. It's very messy.)

Finally, looking closer at the code, I decided that I would implement a `transport.ServerTransport` based on the HTTP2 transport, but with `HandleStreams` overridden to set the deadline on the conn. However, there is no way to provide a custom ServerTransport.

### Proposed Solution

Given that the probably isn't a more general need to set a deadline on a per-connection basis and TLS authentication for gRPC servers is extremely common, I think it would be appropriate to add a new server option to force TLS clients to reconnect when their presented certificate expires. When enabled, the deadline being cleared [here](https://github.com/grpc/grpc-go/blob/v1.23.1/server.go#L663) should instead be set to the peer cert's expiration date.

### Additional Context

I have not yet created a PR, because I wanted feedback and a some acceptance of this proposal, but the change would look like this (plus tests):

```diff
diff --git a/server.go b/server.go
index f064b73e..76724b24 100644
--- a/server.go
+++ b/server.go
@@ -130,6 +130,7 @@ type serverOptions struct {
        readBufferSize        int
        connectionTimeout     time.Duration
        maxHeaderListSize     *uint32
+       forceTLSReconnect     bool
 }

 var defaultServerOptions = serverOptions{
@@ -377,6 +378,14 @@ func MaxHeaderListSize(s uint32) ServerOption {
        })
 }

+// ForceTLSClientReconnect returns a ServerOption that requires TLS peers to
+// reauthenticate when their presented certificate expires.
+func ForceTLSClientReconnect(b bool) ServerOption {
+       return newFuncServerOption(func(o *serverOptions) {
+               o.forceTLSReconnect = b
+       })
+}
+
 // NewServer creates a gRPC server which has no service registered and has not
 // started to accept requests yet.
 func NewServer(opt ...ServerOption) *Server {
@@ -661,6 +670,15 @@ func (s *Server) handleRawConn(rawConn net.Conn) {
        }

        rawConn.SetDeadline(time.Time{})
+       if tlsInfo, ok := authInfo.(credentials.TLSInfo); ok && s.opts.forceTLSReconnect {
+               if peer := tlsInfo.State.PeerCertificates; len(peer) > 0 {
+                       if err := rawConn.SetDeadline(peer[0].NotAfter); err != nil {
+                               grpclog.Warningf("grpc: Server.Serve failed to set deadline on %q: %v", rawConn.RemoteAddr(), err)
+                               rawConn.Close()
+                               return
+                       }
+               }
+       }
        if !s.addConn(st) {
                return
        }
```

**Comment by menghanl** [comment] 2019-09-13 18:09
Would a manual timeout `time.AfterFunc(timeout, func() { rawConn.Close() })` work?

To not leak the timer:

```go
type timeoutTLSConn {
  net.Conn // The TLS conn
  timer *time.Timer
}

func newTimeoutTLSConn(rawConn, tlsconn net.Conn, timeout time.Duration) net.Conn {
  timer := time.AfterFunc(timeout, func() { rawConn.Close() })
  return &timeoutTLSConn{
    Conn: tlsconn,
    timer: timer,
  }  
}

func (c *timeoutTLSConn) Close() error {
  timer.Stop()
  c.Conn.Close()
}
```

**Comment by ben-krieger** [comment] 2019-09-13 18:32
@menghanl Yes, it would work. I forgot to mention that I had also tried an approach similar to this, but considered it a bit inefficient since it spun up an extra goroutine for every connection. However, your code is a bit better than what I wrote up initially since it stops the goroutine if the connection closes.

I think that this is a reasonable approach to take, but utilizing the OS's deadlines directly on the file descriptors seems better if the service scales to a lot of connections. Perhaps I'm prematurely optimizing and the goroutines are even lighter than I imagine. I obviously haven't benchmarked anything.

One more thing is that by returning a wrapped conn, it won't implement the `syscall.Conn` interface anymore, so I'd have to implement that in the `timeoutTLSConn`, correct? Are there any other "bonus" interfaces I should be implementing?

**Comment by menghanl** [comment] 2019-09-13 20:06
If I remember correctly, `time.AfterFunc` doesn't create a new goroutine every time. The golang runtime does special handling for it.

It's not ideal that `SetDeadline` doesn't just work.
One possible solution is for gRPC server to call `SetDeadline()` on the returned conn, instead of on rawConn. I haven't thought through about this, not sure if it has other problems.

On the `syscall.Conn` problem. Unfortunately, yes, you will need to wrap it...
It's only use by channelz (a monitoring service, [gRFC link](https://github.com/grpc/proposal/blob/master/A14-channelz.md)) to get file descriptor level information. So if you don't need that, it should be OK to not implement `syscall.Conn`. But the wrapping is pretty easy to do also.
There is no other hidden interface to implement.

I guess there's no way to get the certificate deadline without doing the handshake, right? Otherwise timeout wrapping can happen before `ServerHandshake()`...

**Comment by ben-krieger** [comment] 2019-09-13 20:14
Thank you for the insight into `time.AfterFunc`. I'll look into that and likely go with that solution for the time being.

If the gRPC server were to call `SetDeadline` on the returned Conn, rather than the raw conn, then I could do something like:

```
type absoluteDeadlineConn struct {
    net.Conn
    deadline time.Time
}

func (c absoluteDeadlineConn) SetDeadline(t time.Time) error {
    if time.IsZero(t) || t.After(c.deadline) {
        return c.Conn.SetDeadline(c.deadline)
    }
    return c.Conn.SetDeadline(t)
}
```

and return that from a custom `ServerHandshake`. This solution would also be perfectly fine by me.

Again, thanks for the help, and I'm okay with closing this issue if you wish, but I think it still might be worth considering adding a new server option or some sort of handle that receives a conn, because wrapping a conn and a TransportCredentials is pretty complex just to set a deadline.

**Comment by menghanl** [comment] 2019-09-17 23:23
The problem with adding the server option is that it will be a special server option for TLS.
A more general way is to add a method to `AuthInfo` interface. But this causes an API change (It would be easier if `AuthInfo` is a struct instead).

Potential problem with `SetDeadline` is, if for any reason, the server wants to set a shorter deadline on the connection, it won't work.
Also I think the root cause the `SetDeadline` doesn't work is that it can only clear all deadlines. What we want here is actually "clear the deadline I set, but keep others".

The AfterFunc solution should work fine for now. I'm closing this issue. Please reply back if you have further concerns.

**Closed by menghanl** 2019-09-17 23:23 UTC
Labels: Type: Feature
