### ISSUE TITLE
balancer: authentication handshake failed

### ISSUE THREAD

**Issue by minaevmike** [grpc/grpc-go#1627] opened 2017-10-26 17:41 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
grpc-go/1.8.0-dev(master
### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64
### What operating system (Linux, Windows, …) and version?
Linux 4.13
### What did you do?
I have self written resolver
```
balancer := grpc.RoundRobin(&myResolver{})
opts = append(opts, grpc.WithBalancer(balancer))
```
After i upgrade to `grpc-go` master. I have very strage errors
```
Failed to dial some-addr-from-resolver.com: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for some-addr-from-resolver.com www.some-addr-from-resolver.com, not some-service"; please retry.
```
I reseacrh a bit and found:
i make dial smth like: `grpc.Dial("some-service", grpc.WithBalancer(balancer))`, it goes to my resolver resolve `some-service` to ` some-addr-from-resolver.com` and try to make `newHttp2Client` but `ac.cc.authority` is set to `some-service` and Authority in `tls.Config` is empty. So i want to know - what is the proper way to implement resolver or something else to set authority to proper value?

### EDIT
I think i found bad change:
```
@@ -131,15 +127,16 @@ func (c tlsCreds) Info() ProtocolInfo {
        }
 }

-func (c *tlsCreds) ClientHandshake(ctx context.Context, addr string, rawConn net.Conn) (_ net.Conn, _ AuthInfo, err error) {
+func (c *tlsCreds) ClientHandshake(ctx context.Context, authority string, rawConn net.Conn) (_ net.Conn, _ AuthInfo, err error) {
        // use local cfg to avoid clobbering ServerName if using multiple endpoints
        cfg := cloneTLSConfig(c.config)
+       fmt.Println(cfg.ServerName)
        if cfg.ServerName == "" {
-               colonPos := strings.LastIndex(addr, ":")
+               colonPos := strings.LastIndex(authority, ":")
                if colonPos == -1 {
-                       colonPos = len(addr)
+                       colonPos = len(authority)
                }
-               cfg.ServerName = addr[:colonPos]
+               cfg.ServerName = authority[:colonPos]
        }
        conn := tls.Client(rawConn, cfg)
        errChannel := make(chan error, 1)

```
grpc-go takes authority from clientconnection, but it doens't respect that authority can be different for each address. So as i can understand this is wrong.
```
		ac.mu.Unlock()
		for _, addr := range addrsIter {
			ac.mu.Lock()
			if ac.state == connectivity.Shutdown {
				// ac.tearDown(...) has been invoked.
				ac.mu.Unlock()
				return errConnClosing
			}
			ac.mu.Unlock()
			sinfo := transport.TargetInfo{
				Addr:      addr.Addr,
				Metadata:  addr.Metadata,
				Authority: ac.cc.authority,
			}
```

**Comment by menghanl** [comment] 2017-10-26 18:10
If I understand correctly, you are doing test with dial target `"some-service"`, while the tls certificate is for `"some-addr-from-resolver.com www.some-addr-from-resolver.com"`.

By default `ServerName` in `tls.Config` will be set to the dial target if it's not overridden (if it's `""`).

If you want to override the `ServiceName`, set the `serverNameOverride` parameter in [`NewClientTLSFromFile`](https://godoc.org/google.golang.org/grpc/credentials#NewClientTLSFromFile) to the server name you want.

**Comment by minaevmike** [comment] 2017-10-26 18:15
@menghanl thank you for your answer.
But with load balancing i can't set `ServiceName`? because i don't know witch server will be choose for connection.
for example, my balancer gives me `addr-01.some-host.com` and `addr-02.some-host.com`, and mb in future one server can be added like `addr-03.some-host321.com`. So i set it to tls.Config, because for each server it must be different authorities.

**Comment by menghanl** [comment] 2017-10-26 18:40
The reason for the change is:
Normally, balancers do pick from __resolved addresses__, not server names.
If we do `ClientHandshake()` using the address returned by balancer, we will use the `IP` not the server name, which results in handshake failures.

Though balancers returning un-resolved names is supported (it's actually supported by `net.Dial` which does the name resolution for you), it's not the expected way.

For you use case, I would suggest create multiple CleintConns for those different servers.

**Comment by minaevmike** [comment] 2017-10-26 19:43
Even if i rewrite my balancer and it would return `IP`'s not server names i can't understand 1 thing.
I have 1 logical connection(`*grpc.ClientConn`) inside it can be load balanced and so on. So it can produce several physical connections to different hosts. But i can set Authority only on logical connection(same authority for different hosts). And in case of load balancing to different servers using one authority will cause a lot of problems. Because while certifcate validation will compare this authority and server name from server certificate.
i will check tomorrow, but i think that this can be cheap fix
```
diff --git a/clientconn.go b/clientconn.go
index 5f5aac4..04c32b7 100644
--- a/clientconn.go
+++ b/clientconn.go
@@ -946,7 +946,11 @@ func (ac *addrConn) resetTransport() error {
                        sinfo := transport.TargetInfo{
                                Addr:      addr.Addr,
                                Metadata:  addr.Metadata,
-                               Authority: ac.cc.authority,
+                       }
+                       if ac.cc.balancerWrapper != nil {
+                               sinfo.Authority = addr.Addr
+                       } else {
+                               sinfo.Authority = ac.cc.authority
                        }
                        newTransport, err := transport.NewClientTransport(ac.cc.ctx, sinfo, copts, timeout)
                        if err != nil {
```

**Comment by menghanl** [comment] 2017-10-30 22:07
The `ClientConn` is a logical connection to one name. There may be multiple connection to the same name, but they should share the same Authority. If you need to connect to multiple servers (with different Authorities), you should consider creating multiple `ClientConn`s.

There's a hacky workaround for this:
Don't install client transport credentials. Install a custom dialer and do the client side handshake in your special dialer. Your dialer will get the address returned by balancer, and you can use that to do the handshake.

**Comment by menghanl** [comment] 2017-11-09 22:35
Closing this issue now as it works as intended.

**Closed by menghanl** 2017-11-09 22:35 UTC
Labels: P2, Type: Bug

**Comment by crazed** [comment] 2017-12-01 20:03
Sorry for commenting on a closed issue, but I'm having a similar issue here. Looks like a custom dialer is the recommended approach. Just wanted to raise the point that others with custom discovery probably don't want the `resolver.Target`'s endpoint to be used for x509 validation provided by `credentials.TransportCredentials`. Would be nice if there was a way to update the `ServerName` to expect in the resolver.
