### ISSUE TITLE
How to make server-stream run in a non-blocking state and handle other requests

### ISSUE THREAD

**Issue by nepu-SidneyYu** [grpc/grpc-go#7460] opened 2024-07-31 03:03 UTC
When I used Grpc Server-Stream to access gpt API(http request, stream Response), I want to return stream-data  to client, but if I run in a non-blocking state to send data, it tell me error "rpc error: code = Canceled desc = context canceled"

```
go utils.Chat(request, func(r *model.Response) {
     if err := stream.Send(&pb.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
		}
})
```

If I run in a blocking state to send data，it cannot handle any grpc request while sending server-stream data, must  wait the server-stream data finished sending data

```
done := make(chan bool)
	go utils.Chat(request, func(r *model.Response) {
		if err := stream.Send(&pb.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
		}
		if r.Stop {
			done <- true
		}
	})
	<-done
```
but if I run in a blocking state and sleep some time After each call to stream. Send，it can handle other grpc request
```
done := make(chan bool)
	go utils.Chat(request, func(r *model.Response) {
		if err := stream.Send(&pb.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
		}
		time.Sleep(500 * time.Millisecond)
		if r.Stop {
			done <- true
		}
	})
	<-done
```

how can I sloved it? Did I use it wrong?

**Comment by nepu-SidneyYu** [comment] 2024-08-01 08:33
@arjan-bal Hello, hope your answer, what should it do can sloved my question, Thanks!

**Comment by arjan-bal** [comment] 2024-08-01 09:58
Hi @nepu-SidneyYu, It's not clear to me how the snippets you shared are called from your server handler methods.
Can you share the method of your server struct that implements the service interface?

Assuming your snippets are place directly inside the handler, like the following:
```go
func (s *server) ServerStream(req *pb.Request, stream pb.YourService_ServerStreamServer) error {
    // Snippet 1, 2 or 3
}
```
1 would not work because the context is per client request and is cancelled when `ServerStream` method returns. You should not return from the method until all the data is sent from the server.

The `ServerStream` should be called concurrently by gRPC if clients send parallel requests, so I need more explaination about the following:
> it cannot handle any grpc request while sending server-stream data, must wait the server-stream data finished sending data.

I don't understand how the sleep in the 3rd snippet effects your server.

It would be good if you can share a minimal client server implementation that I can run to understand whats going on here.

**Comment by nepu-SidneyYu** [comment] 2024-08-01 13:21
@arjan-bal Sure，my proto code as follows
`rpc Chat(ChatRequest) returns (stream ChatResponse){}`

my server code as follows:
```
func (c *ChatManager) Chat(req *blog.ChatRequest, stream blog.Chat_ChatServer) error {
	request := &model.Request{
		Model:       consts.ModelName,
		MaxTokens:   consts.MaxTokens,
		ServiceCode: consts.ServiceCode,
		KeyType:     consts.KeyType,
		Tag:         consts.Tag,
	}
	request.Messages = make([]*model.Message, 0)
	request.Messages = append(request.Messages, &model.Message{
		Role:    "user",
		Content: req.Content,
	})

       //1.  Nomally run and can handle other request 
	done := make(chan bool)
	go utils.Chat(request, func(r *model.Response) {
		if err := stream.Send(&blog.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
		}
		time.Sleep(500 * time.Millisecond)
		if r.Stop {
			done <- true
		}
	})
	<-done

        //2.  canot handle any request
	// go utils.Chat(request, func(r *model.Response) {
	// 	if err := stream.Send(&blog.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
	// 		logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
	// 	}
	// })

        //3.rpc error: code = Canceled desc = context canceled
	// utils.Chat(request, func(r *model.Response) {
	// 	if err := stream.Send(&blog.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
	// 		logs.Error(context.Background(), "stream send error", zap.String("error", err.Error()))
	// 	}
	// })
	return nil
}
```
and the utils.chat as follows:
```
func Chat(req *model.Request, fn func(*model.Response)) error {
	url := "XXXX/chat-llm/v1/completions/stream/multi"
	jsonvalue, _ := json.Marshal(req)
	request, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonvalue))
	if err != nil {
		logs.Error(context.Background(), "create request failed", zap.String("error", err.Error()))
		return err
	}
	request.Header.Set("Content-Type", "application/json")
	client := http.Client{}
	resp, err := client.Do(request)
	if err != nil {
		logs.Error(context.Background(), "request failed", zap.String("error", err.Error()))
		return err
	}
	go func() {
		defer resp.Body.Close()

		reader := bufio.NewReader(resp.Body)
		var respe = new(model.Response)
		//count := 0
		var mess = new(model.Message)
		var result = new(model.Response)
		for {
			line, err := reader.ReadBytes('\n')
			if err != nil {
				logs.Error(context.Background(), "read response body failed", zap.String("error", err.Error()))
				return
			}
			line = bytes.TrimSpace(line)
			if len(line) == 0 {
				continue
			}
			//res := bytes.TrimPrefix(line, []byte("data:"))

			err = json.Unmarshal(line, &result)
			if err != nil {
				logs.Error(context.Background(), "umarshal response body failed", zap.String("error", err.Error()))
				return
			}
			respe.Content = result.Content
			respe.Stop = result.Stop
			mess.Content += result.Content
			fmt.Println(respe.Content)
			fn(respe)
			if result.Stop {
				respe.Stop = true
				mess.Role = "assistant"
				break
			}
		}
	}()
	return nil
}
```

> ```
> go utils.Chat(request, func(r *model.Response) {
>      if err := stream.Send(&pb.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: r.Content}); err != nil {
> 			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
> 		}
> })
> ```
This snippet is run in non-blocking state, I donot use chanel to blocking this function `func (c *ChatManager) Chat(req *blog.ChatRequest, stream blog.Chat_ChatServer)` ，so there was such an error, you can read my server code,The code for each fragment and the errors that occurred are marked above. Hope you can give me an answer. Thanks

**Comment by nepu-SidneyYu** [comment] 2024-08-05 06:32
@arjan-bal hello, Do you have time to help me answer this question?，So far I have not found a solution to this question

**Comment by arjan-bal** [comment] 2024-08-05 17:42
I think I understand what your code is doing now:
1. Accept a grpc server side streaming request.
2. Send out an http request to a remote server which streams the response back.
3. As the remote http server's response is received, stream it back to the grpc client.
4. When the entire response is received from the http server, end the grpc stream.

```
grpc client <-> grpc server <-> http server
```

The problem you're seeing is that without the sleep, your server processes only one request at a time and by adding a 500ms sleep after receiving each message from the http server, the grpc server is able to handle concurrent requests from the client.

I don't have a reason why this would happen.

@nepu-SidneyYu I see that your callback waits for `r.Stop` to be true before writing to the channel:
```
if r.Stop {
    done <- true
}
```
In cases where errors are encountered in `utils.Chat()`, (e.g: http server returns errors or json unmarshalling fails), `fn` will never be called and the grpc handler can get stuck forever. 

Are you able to consistently reproduce the problem? Can you verify that the  `ChatManager.Chat` method is not getting stuck waiting on the channel write forever?

**Comment by nepu-SidneyYu** [comment] 2024-08-06 02:32
@arjan-bal Thanks for your reply, I am sure the utils.Chat() no Errors happen, also the http server Will definitely return `r.stop = true` After all responses are completed.
I think is not my `utils.Chat()`  problem, you can use the loop replace my `utils.Chat() `. it also cannot handle any request until This request has been processed:
```
func Chat(req *model.Request, fn func(*model.Response)) error {
      for i := 0; i < 500; i++ {
		if err := stream.Send(&blog.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: strconv.Itoa(i + 1)}); err != nil {
			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
		}
      }
}
```
![image](https://github.com/user-attachments/assets/4603334e-e6f0-46bf-a5c4-aa281c795216)
![image](https://github.com/user-attachments/assets/478b8067-63de-44c7-9f94-ff8c51679c08)
If I use code as follows, it can handle other request,
```
func Chat(req *model.Request, fn func(*model.Response)) error {
      for i := 0; i < 500; i++ {
                time.Sleep(500 * time.Millisecond)
		if err := stream.Send(&blog.ChatResponse{Code: consts.StatusOK, Msg: consts.StatusSuccess, Content: strconv.Itoa(i + 1)}); err != nil {
			logs.Error(stream.Context(), "stream send error", zap.String("error", err.Error()))
		}
      }
}
```
![image](https://github.com/user-attachments/assets/cea4c829-2244-42bb-b8e2-9c1bed267011)
![image](https://github.com/user-attachments/assets/b5a3be07-8984-4891-81b3-f923f93977c0)
If you have time, you can write two function test it. I donot know why

**Comment by arjan-bal** [comment] 2024-08-06 15:56
@nepu-SidneyYu, I tried to repro this issue using the [routeguide example](https://github.com/grpc/grpc-go/tree/master/examples/route_guide) that we have. I started 3 concurrently. In each stream, the server sends back 100 messages. When the stream got a response from the server, it logged the stream number and the message number. What I see is that the responses to the streams are interleaved:
To start the server:
```Go
go run ./server/server.go
```
Then in a different terminal, start the client:
```Go
go run ./client/client.go
```
See the output attached.
[output.txt](https://github.com/user-attachments/files/16512713/output.txt)

**Comment by arjan-bal** [comment] 2024-08-06 20:54
@nepu-SidneyYu can you try making these concurrent calls using a grpc-go client in a Go program instead of Postman and see if they run in parallel?

**Comment by nepu-SidneyYu** [comment] 2024-08-07 07:33
@arjan-bal I use your example to test my code, There is no problem. Because I use one computer and on Postman client to request two requests(one is block, another is non-block), If not sleep, only one request can be processed. But when I use two computer and two Postman client to request two requests(one is blocking, another is non-blocking. ror all are blocking), it's also no problem. So I think it's Postman's problem. 

Thank you for your patience. Wish you a happy life.
Thanks.

**Comment by arjan-bal** [comment] 2024-08-07 10:03
Glad to know that gRPC is working as expected. Closing this issue.

**Closed by arjan-bal** 2024-08-07 10:03 UTC
Labels: Type: Question, Status: Requires Reporter Clarification
