### ISSUE TITLE
Keepalive pings are sent every [Time + Timeout] period; not every [Time] period

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#2638] opened 2019-02-12 21:40 UTC

**Comment by jhump** [comment] 2019-05-11 14:20
I think this is the root cause for a bug filed against grpcurl, too: https://github.com/fullstorydev/grpcurl/issues/99

**Comment by jhump** [comment] 2019-09-06 16:39
@dfawley, I take it you are on top of the misattribution of "stale" to all of these and I should be able to just ignore the GH notifications I am getting?

**Comment by dfawley** [comment] 2019-09-06 16:46
@jhump - Correct.  I am still interested in discussion on #2909, however.  :)

**Comment by easwars** [comment] 2019-10-24 03:36
https://github.com/grpc/grpc-go/pull/3102 fixes the issue on the client side. A similar fix on the server side is required.

**Comment by easwars** [comment] 2019-11-21 19:31
This is fixed now, on both client and server side.

**Closed by easwars** 2019-11-21 19:31 UTC
Labels: P2, Type: Bug
