### ISSUE TITLE
how to support go modules mode

### ISSUE THREAD

**Issue by orange-jacky** [grpc/grpc-go#2546] opened 2018-12-29 02:07 UTC
macbookpro:~ fredlee$ go version
go version go1.12beta1 darwin/amd64
macbookpro:~ fredlee$ echo $GO111MODULE
on
macbookpro:~ fredlee$ go get -u google.golang.org/grpc
go: finding github.com/golang/glog latest
go: finding google.golang.org/genproto latest
go: finding cloud.google.com/go v0.26.0
go: finding golang.org/x/lint latest
go: finding golang.org/x/net latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/sync latest
go: finding github.com/golang/lint latest
go: finding golang.org/x/sys latest
go get: upgrading honnef.co/go/tools@v0.0.0-20180728063816-88497007e858: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: net/http: TLS handshake timeout)
go: cloud.google.com/go@v0.26.0: unknown revision v0.26.0
go get: error loading module requirements

**Comment by menghanl** [comment] 2019-01-02 18:36
> https fetch: Get honnef.co/go/tools?go-get=1: net/http: TLS handshake timeout

This could be caused by connection problems. Can you try again with VPN?

**Comment by orange-jacky** [comment] 2019-01-03 06:59
macbookpro:~ fredlee$ go get -u google.golang.org/grpc
go: finding github.com/golang/glog latest
go: finding cloud.google.com/go v0.26.0
go: finding google.golang.org/genproto latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/net latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/sync latest
go: finding github.com/golang/lint latest
go: finding honnef.co/go/tools latest
go: cloud.google.com/go@v0.26.0: unknown revision v0.26.0
go get: error loading module requirements

**Comment by menghanl** [comment] 2019-01-03 17:46
> go: cloud.google.com/go@v0.26.0: unknown revision v0.26.0

v0.26.0 release exists, but not found for some reason:
https://github.com/googleapis/google-cloud-go/releases/tag/v0.26.0

Did you run everything with VPN? IIRC, to access cloud.google.com you will need VPN.

**Comment by menghanl** [comment] 2019-01-10 21:19
Closing this now. Please reply if you have further questions.

**Closed by menghanl** 2019-01-10 21:19 UTC
Labels: Status: Requires Reporter Clarification, Type: Question
