### ISSUE TITLE
Cert existence not checked before attempting to open conns

### ISSUE THREAD

**Issue by jadekler** [grpc/grpc-go#1768] opened 2017-12-22 23:20 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

Latest code 7f2472bbc6ac269af51a9c47ae8ef8c625383e1f

### What version of Go are you using (`go version`)?

1.8.1

### What operating system (Linux, Windows, …) and version?

alpine:latest

### What did you do?
If possible, provide a recipe for reproducing the error.

```
package main

import (
	"cloud.google.com/go/pubsub"
	"context"
	"fmt"
	"log"
)

func main() {
	fmt.Println("Starting")

	projectId := "<whatever>"

	ctx := context.Background()

	fmt.Println("Getting client")

	client, err := pubsub.NewClient(ctx, projectId) // this hangs forever
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	fmt.Println("Done", client)
}
```

```
FROM golang:1.8-alpine

ADD . /go
RUN go install hanging_problem

FROM alpine:latest
COPY --from=0 /go/bin/hanging_problem .
COPY --from=0 /go/src/deklerk-startup-project/pusher/creds.json /tmp/creds.json

ENV GOOGLE_APPLICATION_CREDENTIALS "/tmp/creds.json"
ENV GRPC_GO_LOG_SEVERITY_LEVEL "INFO"

CMD ["./hanging_problem"]
```

### What did you expect to see?

`client, err` should return `<nil>, transport: authentication handshake failed: x509: failed to load system roots and no roots provided`

### What did you see instead?

Infinite hang

### Question for maintainers

I've spent time trying to fix this problem. Most of the problem is around [clientconn.go](https://github.com/grpc/grpc-go/blob/master/clientconn.go). 

There's a hiccup that I'd like some guidance on, though, largely around being unfamiliar with this codebase. The main `DialContext` thread goes: 

```
(thread1) 
DialContext -> newCCResolverWrapper(..) -> rb.Build(..) -> go bw.lbWatcher() -> (back up to DialContext) -> cc.WaitForStateChange(..) # hangs here

(thread2)
lbWatcher() -> sc.Connect() -> acbw.ac.connect() -> go func() { .. } # Starts a goroutine connecting async

(thread3)
go func() { .. } -> ac.resetTransport() -> ac.createTransport(..) -> transport.NewClientTransport(..) # this returns the error mentioned about - transport: authentication handshake failed
```

So, thread 3 gets the error but thread 1 is waiting for updates that never arrive. After a second or two all retries are exhausted and thread 1 hangs forever. 

My question is, what is the appropriate means for thread 3 to communicate to thread 1 that an unrecoverable exception has occurred?

Alternatively, is it more appropriate to check for the existence of certs before creating the resolvers and going down that chain?

One more, less-good option; adding a default deadline to `WaitForStateChange` (it uses `context.Background()`, which never times out).

**Comment by jadekler** [comment] 2017-12-22 23:28
Small note - in my example I use `pubsub.NewClient`, which if you follow its calls down ends up at `grpc.DialContext`: `pubsub.NewClient` hangs on `transport.DialGRPC -> gtransport.Dial -> dial -> grpc.DialContext`

**Comment by menghanl** [comment] 2017-12-27 21:59
This is a duplicate of #1633. The cert is checked, but grpc.Dial doesn't return the error.
We will have a cleanup on ClientConn to handle this. Tracked in #1742.

**Closed by menghanl** 2017-12-27 21:59 UTC

**Comment by jadekler** [comment] 2017-12-30 03:19
Ah ok, thanks @menghanl

**Comment by dfawley** [comment] 2018-01-02 21:15
Regarding this point:

> One more, less-good option; adding a default deadline to `WaitForStateChange` (it uses `context.Background()`, which never times out).

[`WaitForStateChange`](https://godoc.org/google.golang.org/grpc#ClientConn.WaitForStateChange) accepts a `context.Context` parameter.  In your thread1, this is the one provided by the user when they called `grpc.DialContext`.  This can only be `context.Background()` if that's the one the user provided (as you show happening above in the call to `pubsub.NewClient`) or if `grpc.Dial` is called without the `grpc.WithTimeout()` `DialOption`.  Otherwise, `Dial[Context]` should never hang indefinitely.

**Comment by jadekler** [comment] 2018-01-03 04:56
@dfawley Ah, good point, thanks. I read [cc.ctx, cc.cancel = context.WithCancel(context.Background())](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L418) and conflated it with `ctx` (passed in as a param).
