### ISSUE TITLE
Reuse receive buffer

### ISSUE THREAD

**Issue by kerinin** [grpc/grpc-go#869] opened 2016-08-28 15:37 UTC
I've been considering using flatbuffers in place of protobufs in a service that does a lot of "proxying" to reduce GC load.  It would be even better if the client parser reused its receive buffer as listed as a "TODO" here https://github.com/grpc/grpc-go/blob/v1.0.1-GA/rpc_util.go#L244-L246

Is this on the roadmap?

**Comment by iamqizhao** [comment] 2016-08-30 17:58
yeah, it is part of performance optimization we will focus on shortly.

**Comment by jmacd** [comment] 2016-10-31 16:21
We've looked for ways to reduce memory pressure caused by inbound RPC processing, and there aren't any ways to throttle these allocations we can find. Either I would like to re-use these buffers (ideally, have an upper bound on number of buffers) or be provided with a way to intercept the request and stall before its buffer is allocated (as requested here: https://github.com/grpc/grpc-go/issues/901).

As it stands, there's no way to prevent a new request on an existing stream from allocating a new buffer immediately, since it happens before the existing interceptor support.

There's no way to selectively drain a client, either. (https://github.com/grpc/grpc-go/blob/71d2ea4f75286a63b606aca2422cd17ff37fd5b8/transport/handler_server.go#L373)

Just a quote from the code, as a signal boost.
// TODO(bradfitz,zhaoq): garbage. reuse buffer after proto decoding instead
https://github.com/grpc/grpc-go/blob/71d2ea4f75286a63b606aca2422cd17ff37fd5b8/rpc_util.go#L244

**Comment by jmacd** [comment] 2016-10-31 16:22
(^^^ this issue is not about an optimization, this is about unruly behavior. please prioritize.)

**Comment by therc** [comment] 2016-10-31 16:34
There's a similar issue on the C side: https://github.com/grpc/grpc/issues/8187

**Comment by mwitkow** [comment] 2017-04-03 10:20
@MakMukhi any chance this gets prioritised? :)

**Comment by hsaliak** [comment] 2017-05-17 23:31
@apolcyn assigning this to you to take a look. /cc @dfawley

**Comment by irfansharif** [comment] 2017-08-29 04:06
can I take this on? I have a draft I can polish up for submission if nobody else is already working on this/something orthogonal/supplanting it entirely.

**Comment by MakMukhi** [comment] 2017-08-29 17:24
Don't worry about polishing it, point us to the rough draft and we can discuss how to move forward from there. 

A few things that we care about are:
1. Benchmark numbers comparing a sync.Pool to a [leaky buffer](https://golang.org/doc/effective_go.html#leaky_buffer) cache.
2. Benchmark numbers for not just memory profile but latency and corresponding CPU profile. Please take a look at our existing benchmark [code](https://github.com/grpc/grpc-go/tree/master/benchmark/benchmain).

A few thoughts:
Given the messages are going to be of different sizes how are you planning to deal with that? A cache with different buffer sizes or a cache in which buffer sizes eventually grow with the message sizes seen. 

If you go with sync.Pool all the cached memory will be released every GC cycle, it'll be interesting to see if that affects performance. Therefore latency benchmarks with CPU profiling are interesting.
If you go with a leakyBuffer, how are you planning to reclaim memory?

**Comment by MakMukhi** [comment] 2017-12-14 22:49
This is now tracked by #1455

**Closed by MakMukhi** 2017-12-14 22:49 UTC
Labels: P2, Type: Performance
