### ISSUE TITLE
Fail to build docker image

### ISSUE THREAD

**Issue by adelez** [grpc/grpc-go#1146] opened 2017-03-24 21:00 UTC
Interop tests are failing to build Go docker image:
https://grpc-testing.appspot.com/job/gRPC_interop_master/11866/console
go get -d -v -t google.golang.org/grpc/...
# google.golang.org/grpc/transport
../../transport/http2_client.go:130: undefined: dialContext

**Comment by adelez** [comment] 2017-03-24 21:01
@muxi

**Comment by menghanl** [comment] 2017-03-24 21:18
The go version used is 1.5. It doesn't work after #1132.

**Comment by menghanl** [comment] 2017-03-24 21:28
https://github.com/grpc/grpc/pull/10309 filed for this.

**Comment by ericgribkoff** [comment] 2017-03-30 16:45
The Go docker image failed to build at https://grpc-testing.appspot.com/job/gRPC_interop_master/12001/console and https://grpc-testing.appspot.com/job/gRPC_interop_master/12006/console, both since this fix was merged. I rebuilt 12006 and it passed, but building Go is still flaky for some reason.

**Comment by ericgribkoff** [comment] 2017-03-30 18:51
This might be a different error than originally reported here. I can reproduce the failure locally about one out of ten runs of the `run_interop_tests.py` script. Output [here](https://gist.github.com/ericgribkoff/f6936d0a54c2fedf556f2a7b90f588ef). I'm not too familiar with Go, but looks like it's running into a problem when fetching dependencies. Is this an issue with a third-party that we're just encountering intermittently?

**Comment by dfawley** [comment] 2017-03-30 19:33
Yes, that is unrelated; this issue was about go1.5.  The error from yours says:

```
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 404)
package golang.org/x/oauth2: unrecognized import path "golang.org/x/oauth2" (parse https://golang.org/x/oauth2?go-get=1: no go-import meta tags ())
```

I don't know what could be causing that.

**Comment by dfawley** [comment] 2017-03-30 19:54
Best guess is maybe https://github.com/grpc/grpc/pull/10309, which changed to use go-latest instead of go1.5, and go-latest is unstable.  Is it possible for you to test with the go1.8 version and see if that's more reliable?

**Comment by ericgribkoff** [comment] 2017-03-31 16:49
It seems to have been a transient failure. The Go docker image failed to build twice in a row yesterday morning, but it's been stable on master since.

**Closed by ericgribkoff** 2017-03-31 16:49 UTC
